# La base de NumPy - ndarray

Toda la librería de NumPy se articula alrededor de una única estructura de datos: la matriz multidimensional o ndarray (N-dimensional array)

### Características básicas de ndarray

- Un ndarray puede contener elementos de <b>CUALQUIER TIPO</b>.
- Todos los elementos de un ndarray debn tener el <b>EL MISMO TIPO</b>.
- El tamaño de un ndarray (número de elementos) se define en el momento de la creación y no puede modificarse.
- Pero la organización de estos elementos entre diferentes dimensiones sí pueden modificarse.

### Uso básico de cualquier elemento de NumPy

NumPy no es un módulo de Python por lo que SIEMPRE habrá que importarlo de forma completa o componente a componente

In [5]:
import numpy as np

### Creación básica de ndarrays

Existen varias formas de crear un ndarray en NumPy. Vamos a ver las más relevantes.

#### Creación de un ndarray vacío

In [51]:
array_vacio_float = np.empty((2,2))            # dtype=float by default
print("float:\n", array_vacio_float, "\n")

array_vacio_int = np.empty(shape=(2,3), dtype=np.int32)
print("int:\n", array_vacio_int, "\n")

array_vacio_copia = np.empty_like([1,2,3,4,5]) # Return a new array with the same shape and type as a given array.
print("copia:\n", array_vacio_copia, "\n" )

array_vacio_copia2 = np.empty_like(([1,2,3], [4,5,6]))
print("copia2:\n", array_vacio_copia2)

float:
 [[2.12199579e-314 9.34609110e-307]
 [5.65211099e-321 1.18407365e-311]] 

int:
 [[1 2 3]
 [4 5 6]] 

copia:
 [1 2 3 4 5] 

copia2:
 [[1 2 3]
 [4 5 6]]


#### Creación de un ndarray de unos

In [57]:
array_unos_float = np.ones((2,2))
print("float:\n", array_unos_float, "\n")

array_unos_int = np.ones((2,2), dtype=np.int32)
print("int:\n", array_unos_int, "\n")

array_unos_copia = np.ones_like([1,2,3,4,5])
print("copia:\n", array_unos_copia, "\n")

float:
 [[1. 1.]
 [1. 1.]] 

int:
 [[1 1]
 [1 1]] 

copia:
 [1 1 1 1 1] 



#### Creación de un ndarray de ceros

In [59]:
array_ceros_float = np.zeros((2,2))
print("float:\n", array_ceros_float, "\n")


array_ceros_int = np.zeros((2,2), dtype=int)
print("int:\n", array_ceros_int, "\n")


array_ceros_copia = np.zeros_like([1,2,3,4])
print("copia:\n", array_ceros_copia, "\n")

float:
 [[0. 0.]
 [0. 0.]] 

float:
 [[0 0]
 [0 0]] 

float:
 [0 0 0 0] 



#### Creación de un ndarray con la matriz identidad

In [64]:
array_identidad_float = np.identity(5)
print("float:\n", array_identidad_float, "\n")

array_identidad_int = np.identity(5, dtype=int)
print("int:\n", array_identidad_int, "\n") 

float:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

int:
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] 



#### Creación de un ndarray con unos en una de las diagonales

In [82]:
array_identidad_float = np.eye(4)
print("float:\n", array_identidad, "\n")

array_identidad_int = np.eye(4, dtype=int)
print("int:\n", array_identidad, "\n")

array_segunda_diagonal = np.eye(4, k=1)
print("segunda diagonal:\n", array_segunda_diagonal, "\n")

array_no_cuadrado = np.eye(4,3,k=-1,dtype=int)
print("no cuadrado:\n", array_no_cuadrado, "\n")

float:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 

int:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 

segunda diagonal:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]] 

no cuadrado:
 [[0 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]] 



#### Creación de un ndarray a partir de una secuencia básica de Python

In [32]:
array_basico = np.array([1,2,3,4,5,6])
print("array_basico:\n",array_basico)

array_basico_tipo = np.array([1,2,3,4,5,6], dtype=np.int64)
print("array_basico_tipo:\n", array_basico_tipo)

array_basico_multidimencional = np.array([[1,2,3,4],[5,6,7,8]])
print("array_basico_multidimencional:\n", array_basico_multidimencional)

array_basico:
 [1 2 3 4 5 6]
array_basico_tipo:
 [1 2 3 4 5 6]
array_basico_multidimencional:
 [[1 2 3 4]
 [5 6 7 8]]


### Tipos de dato en ndarrays de NumPy

<ul>
<li><b>Enteros con signo:</b> np.int8, np.int16, np.int32 y np.int64</li>
<li><b>Enteros sin signo:</b> np.uint8, np.uint16, np.uint32 y np.uint64</li>
<li><b>Números en coma flotante:</b> np.float16, np.float32, np.float64, np.float128</li>
<li><b>Números complejos:</b> np.complex64, np.complex128, np.complex256</li>
<li><b>Booleanos:</b> np.bool</li>
<li><b>Objetos:</b> np.object</li>
<li><b>Cadenas de caracteres:</b> np.string\_</li>
<li><b>Cadenas de caracteres unicode:</b> np.unicode\_</li>
</ul>

### Casting/Conversión entre ndarrays

In [34]:
array_inicial = np.array([1,2,3,4,5], dtype=np.int32)
print("array inicial ",array_inicial)

array_float = np.asarray(array_inicial, dtype=np.float64)
print("casting a float ",array_float)

array_string = np.asarray(array_float, dtype=np.str_)
print("casting a string ",array_string)

array inicial  [1 2 3 4 5]
casting a float  [1. 2. 3. 4. 5.]
casting a string  ['1.0' '2.0' '3.0' '4.0' '5.0']


### Consulta de la composición de un ndarray