# La base de NumPy - ndarray

Toda la librería de NumPy se articula alrededor de una única estructura de datos: la matriz multidimensional o ndarray (N-dimensional array)

### Características básicas de ndarray

- Un ndarray puede contener elementos de <b>CUALQUIER TIPO</b>.
- Todos los elementos de un ndarray debn tener el <b>EL MISMO TIPO</b>.
- El tamaño de un ndarray (número de elementos) se define en el momento de la creación y no puede modificarse.
- Pero la organización de estos elementos entre diferentes dimensiones sí pueden modificarse.

### Uso básico de cualquier elemento de NumPy

NumPy no es un módulo de Python por lo que SIEMPRE habrá que importarlo de forma completa o componente a componente

In [5]:
import numpy as np

### Creación básica de ndarrays

Existen varias formas de crear un ndarray en NumPy. Vamos a ver las más relevantes.

#### Creación de un ndarray vacío

In [51]:
array_vacio_float = np.empty((2,2))            # dtype=float by default
print("float:\n", array_vacio_float, "\n")

array_vacio_int = np.empty(shape=(2,3), dtype=np.int32)
print("int:\n", array_vacio_int, "\n")

array_vacio_copia = np.empty_like([1,2,3,4,5]) # Return a new array with the same shape and type as a given array.
print("copia:\n", array_vacio_copia, "\n" )

array_vacio_copia2 = np.empty_like(([1,2,3], [4,5,6]))
print("copia2:\n", array_vacio_copia2)

float:
 [[2.12199579e-314 9.34609110e-307]
 [5.65211099e-321 1.18407365e-311]] 

int:
 [[1 2 3]
 [4 5 6]] 

copia:
 [1 2 3 4 5] 

copia2:
 [[1 2 3]
 [4 5 6]]


#### Creación de un ndarray de unos

In [57]:
array_unos_float = np.ones((2,2))
print("float:\n", array_unos_float, "\n")

array_unos_int = np.ones((2,2), dtype=np.int32)
print("int:\n", array_unos_int, "\n")

array_unos_copia = np.ones_like([1,2,3,4,5])
print("copia:\n", array_unos_copia, "\n")

float:
 [[1. 1.]
 [1. 1.]] 

int:
 [[1 1]
 [1 1]] 

copia:
 [1 1 1 1 1] 



#### Creación de un ndarray de ceros

In [59]:
array_ceros_float = np.zeros((2,2))
print("float:\n", array_ceros_float, "\n")


array_ceros_int = np.zeros((2,2), dtype=int)
print("int:\n", array_ceros_int, "\n")


array_ceros_copia = np.zeros_like([1,2,3,4])
print("copia:\n", array_ceros_copia, "\n")

float:
 [[0. 0.]
 [0. 0.]] 

float:
 [[0 0]
 [0 0]] 

float:
 [0 0 0 0] 



#### Creación de un ndarray con la matriz identidad

In [64]:
array_identidad_float = np.identity(5)
print("float:\n", array_identidad_float, "\n")

array_identidad_int = np.identity(5, dtype=int)
print("int:\n", array_identidad_int, "\n") 

float:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

int:
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] 



#### Creación de un ndarray con unos en una de las diagonales

In [82]:
array_identidad_float = np.eye(4)
print("float:\n", array_identidad, "\n")

array_identidad_int = np.eye(4, dtype=int)
print("int:\n", array_identidad, "\n")

array_segunda_diagonal = np.eye(4, k=1)
print("segunda diagonal:\n", array_segunda_diagonal, "\n")

array_no_cuadrado = np.eye(4,3,k=-1,dtype=int)
print("no cuadrado:\n", array_no_cuadrado, "\n")

float:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 

int:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 

segunda diagonal:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]] 

no cuadrado:
 [[0 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]] 



#### Creación de un ndarray a partir de una secuencia básica de Python

In [32]:
array_basico = np.array([1,2,3,4,5,6])
print("array_basico:\n",array_basico)

array_basico_tipo = np.array([1,2,3,4,5,6], dtype=np.int64)
print("array_basico_tipo:\n", array_basico_tipo)

array_basico_multidimencional = np.array([[1,2,3,4],[5,6,7,8]])
print("array_basico_multidimencional:\n", array_basico_multidimencional)

array_basico:
 [1 2 3 4 5 6]
array_basico_tipo:
 [1 2 3 4 5 6]
array_basico_multidimencional:
 [[1 2 3 4]
 [5 6 7 8]]


### Tipos de dato en ndarrays de NumPy

<ul>
<li><b>Enteros con signo:</b> np.int8, np.int16, np.int32 y np.int64</li>
<li><b>Enteros sin signo:</b> np.uint8, np.uint16, np.uint32 y np.uint64</li>
<li><b>Números en coma flotante:</b> np.float16, np.float32, np.float64, np.float128</li>
<li><b>Números complejos:</b> np.complex64, np.complex128, np.complex256</li>
<li><b>Booleanos:</b> np.bool</li>
<li><b>Objetos:</b> np.object</li>
<li><b>Cadenas de caracteres:</b> np.string\_</li>
<li><b>Cadenas de caracteres unicode:</b> np.unicode\_</li>
</ul>

### Casting/Conversión entre ndarrays

In [34]:
array_inicial = np.array([1,2,3,4,5], dtype=np.int32)
print("array inicial ",array_inicial)

array_float = np.asarray(array_inicial, dtype=np.float64)
print("casting a float ",array_float)

array_string = np.asarray(array_float, dtype=np.str_)
print("casting a string ",array_string)

array inicial  [1 2 3 4 5]
casting a float  [1. 2. 3. 4. 5.]
casting a string  ['1.0' '2.0' '3.0' '4.0' '5.0']


### Consulta de la composición de un ndarray

<ul>
<li><b>dtype</b>: Tipo del contenido del ndarray.</li>
<li><b>ndim</b>: Número de dimensiones/ejes del ndarray.</li>
<li><b>shape</b>: Estructura/forma del ndarray, es decir, número de elementos en cada uno de los ejes/dimensiones.</li>
<li><b>size</b>: Número total de elementos en el ndarray.</li>
</ul>

In [43]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("array:\n",array)
print("tipo:\n", array.dtype)
print("número de dimensiones:\n", array.ndim)
print("forma:\n", array.shape)
print("número de elementos\n", array.size)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
tipo:
 int32
número de dimensiones:
 2
forma:
 (3, 4)
número de elementos
 12


In [41]:
array = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

print("array:\n",array)
print("tipo:\n", array.dtype)
print("número de dimensiones:\n", array.ndim)
print("forma:\n", array.shape)
print("número de elementos\n", array.size)

array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
tipo:
 int32
número de dimensiones:
 3
forma:
 (2, 2, 4)
número de elementos
 16


### Operaciones aritméticas entre ndarrays y escalares

In [53]:
array = np.array([1,2,3,4,5,6], dtype=np.float64)

print("suma:            ", array + 5)
print("resta:           ", array - 2)
print("multiplicación:  ", array * 3)
print("división:        ", array / 2)
print("división entera: ", array // 2)
print("potencia:        ", array ** 2)

suma:             [ 6.  7.  8.  9. 10. 11.]
resta:            [-1.  0.  1.  2.  3.  4.]
multiplicación:   [ 3.  6.  9. 12. 15. 18.]
división:         [0.5 1.  1.5 2.  2.5 3. ]
división entera:  [0. 1. 1. 2. 2. 3.]
potencia:         [ 1.  4.  9. 16. 25. 36.]


In [99]:
array = np.array([1,2,3,4,5,6], dtype=np.float64)

print("asignación con operador:") # se modifica el array

array += 5
print("suma:            ", array)

array -= 2
print("resta:           ", array)

array *= 3
print("multiplicación:  ", array)

array /= 2
print("división:        ", array)

array //= 2
print("división entera: ", array)

array **= 2
print("potencia:        ", array)

asignación con operador:
suma:             [ 6.  7.  8.  9. 10. 11.]
resta:            [4. 5. 6. 7. 8. 9.]
multiplicación:   [12. 15. 18. 21. 24. 27.]
división:         [ 6.   7.5  9.  10.5 12.  13.5]
división entera:  [3. 3. 4. 5. 6. 6.]
potencia:         [ 9.  9. 16. 25. 36. 36.]


### Operaciones aritméticas entre ndarrays

<b>IMPORTANTE:</b> Los dos términos de la operación tienen que ser ndarrays de las mismas dimensiones y forma. Se aplica la operación elemento a elemento.

In [97]:
array = np.array([1.0,2,3,4,5])

print("suma            (elemento a elemento): ", array +  array)
print("resta           (elemento a elemento): ", array -  array)
print("multiplicación  (elemento a elemento): ", array *  array)
print("división        (elemento a elemento): ", array /  array)
print("división entera (elemento a elemento): ", array // array)
print("potencia        (elemento a elemento): ", array ** array)


float64
suma            (elemento a elemento):  [ 2.  4.  6.  8. 10.]
resta           (elemento a elemento):  [0. 0. 0. 0. 0.]
multiplicación  (elemento a elemento):  [ 1.  4.  9. 16. 25.]
división        (elemento a elemento):  [1. 1. 1. 1. 1.]
división entera (elemento a elemento):  [1. 1. 1. 1. 1.]
potencia        (elemento a elemento):  [1.000e+00 4.000e+00 2.700e+01 2.560e+02 3.125e+03]


In [106]:
array_1 = np.array([1,2,3], dtype=np.float64)
array_2 = np.array([1,6,7],  dtype=np.float64)
array_3 = np.array([9,6,2],  dtype=np.float64)


print("asignación con operador:") # se modifica el array

array_1 += array_2
print("suma:            ", array_1)
array_1 -= array_3
print("resta:           ", array_1)
array_1 *= array_2
print("multiplicación:  ", array_1)
array_1 /= array_3
print("división:        ", array_1)
array_1 //= array_2
print("división entera: ", array_1)
array_1 **= array_1
print("potencia:        ", array_1)

asignación con operador:
suma:             [ 2.  8. 10.]
resta:            [-7.  2.  8.]
multiplicación:   [-7. 12. 56.]
división:         [-0.77777778  2.         28.        ]
división entera:  [-1.  0.  4.]
potencia:         [ -1.   1. 256.]


### Indexación y slicing básico

En ndarrays unidimensionales el funcionamiento es idéntico al que se tiene en secuencias básicas de Python. Es decir, se utiliza la indexación [a:b:c].

In [126]:
array = np.arange(1,11)

print("array: ", array)
print("indexación con primer parámetro:          ", array[2])
print("indexación con primer y segunda parámetro:", array[2:5])
print("indexación con tercer parámetro           ", array[::2])
print("indexación con negativos:                 ", array[::-2])

array:  [ 1  2  3  4  5  6  7  8  9 10]
indexación con primer parámetro:           3
indexación con primer y segunda parámetro: [3 4 5]
indexación con tercer parámetro            [1 3 5 7 9]
indexación con negativos:                  [10  8  6  4  2]


En ndarrays multidimensionales, existen dos posibles formas de realizar el acceso:<br/>
<ul>
<li><b>Mediante indexación recursiva:</b> array[a:b:c en dim_1][a:b:c en dim_2]...[a:b:c en dim_n]</li>
<li><b>Mediante indexación con comas:</b> array[a:b:c en dim_1, a:b:c en dim_2, ...a:b:c en dim_n]</li>
</ul>

In [149]:
array = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

print(array, "\n")
print("número de dimensiones:", array.ndim)
print("forma de la matriz:   ", array.shape, "\n")

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

número de dimensiones: 3
forma de la matriz:    (2, 2, 4) 



In [152]:
print("indexación recursiva primer nivel:\n", array[1], "\n")
print("indexación recursiva de segundo nivel:\n", array[1][0], "\n")
print("indexación recursiva de tercer nivel:\n", array[1][0][3], "\n")

print("indexación recursiva tercer nivel con slice:\n", array[1][0][::2], "\n")
print("Indexación recursiva tercer nivel con slice de índice negativo:\n", array[0][0][::-1])

indexación recursiva primer nivel:
 [[ 9 10 11 12]
 [13 14 15 16]] 

indexación recursiva de segundo nivel:
 [ 9 10 11 12] 

indexación recursiva de tercer nivel:
 12 

indexación recursiva tercer nivel con slice:
 [ 9 11] 

Indexación recursiva tercer nivel con slice de índice negativo:
 [4 3 2 1]


In [155]:
print("indexación con comas primer nivel:\n", array[1], "\n")
print("indexación con comas de segundo nivel:\n", array[1,0], "\n")
print("indexación con comas de tercer nivel:\n", array[1,0,3], "\n")

print("indexación con comas de tercer nivel con slice:\n", array[1,0,::2], "\n")
print("indexación con comas de tercer nivel con slice negativo:\n", array[1,0,::-1], "\n")

indexación con comas primer nivel:
 [[ 9 10 11 12]
 [13 14 15 16]] 

indexación con comas de segundo nivel:
 [ 9 10 11 12] 

indexación con comas de tercer nivel:
 12 

indexación con comas de tercer nivel con slice:
 [ 9 11] 

indexación con comas de tercer nivel con slice negativo:
 [12 11 10  9] 



### Indexación y slicing booleano

In [190]:
personas = np.array(['Miguel', 'Pedro', 'juan', 'Miguel'])
datos = np.random.randn(4,4)

print(personas, "\n")
print(datos, "\n")

print("indexación/slicing booleano sobre valores:\n", datos[datos < 0], "\n")
print("indexación/slicing mediante máscara y básico combinado:\n", datos[personas=='Miguel',::2], "\n")
print("indexación/slicing mediante máscara negativa por operador:\n", datos[personas!= 'Miguel'])


['Miguel' 'Pedro' 'juan' 'Miguel'] 

[[-0.17650937  0.83020376 -0.00265964  0.10798691]
 [ 1.15077897 -0.48132027  2.15449095 -1.33865479]
 [ 0.64952864 -0.1044879  -0.21323437 -0.8255077 ]
 [ 1.17262884  1.40701482  1.58203368  0.19123016]] 

indexación/slicing booleano sobre valores:
 [-0.17650937 -0.00265964 -0.48132027 -1.33865479 -0.1044879  -0.21323437
 -0.8255077 ] 

[[-0.17650937  0.83020376 -0.00265964  0.10798691]
 [ 1.17262884  1.40701482  1.58203368  0.19123016]]
indexación/slicing mediante máscara y básico combinado:
 [[-0.17650937 -0.00265964]
 [ 1.17262884  1.58203368]] 

indexación/slicing mediante máscara negativa por operador:
 [[ 1.15077897 -0.48132027  2.15449095 -1.33865479]
 [ 0.64952864 -0.1044879  -0.21323437 -0.8255077 ]]
