# Operaciones sobre ndarrays

NumPy pone a nuestra disposición un amplio conjunto de funciones optimizadas para aplicar sobre ndarrays de forma global evitando así la necesidad de utilizar bucles (mucho más costosos).

In [1]:
import numpy as np

import warnings; warnings.simplefilter('ignore')

### Operaciones elemento a elemento - Universal functions

El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas "funciones universales" (o ufuncs) que permiten la realización de operaciones elemento a elemento de un array. En función del número de parámetros encontramos dos tipos de funciones universales.

#### Funciones unarias

Son aquellas funciones que reciben como parámetro un único ndarray.<br/>
<ul>
<li><b>abs, fabs:</b> Valor absoluto.</li>
<li><b>sqrt:</b> Raíz cuadrada (equivalente a array \*\* 0.5).</li>
<li><b>square:</b> Potencia al cuadrado (equivalente a array ** 2).</li>
<li><b>exp:</b> Potencia de e.</li>
<li><b>log, log10, log2, log1p:</b> Logaritmos en distintas bases.</li>
<li><b>sign:</b> Signo (+ = 1 / - = -1 / 0 = 0).</li>
<li><b>ceil:</b> Techo.</li>
<li><b>floor:</b> Suelo.</li>
<li><b>rint:</b> Redondeo al entero más cercano.</li>
<li><b>modf:</b> Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.</li>
<li><b>isnan:</b> Devuelve un array booleano indicando si el valor es NaN o no.</li>
<li><b>isfinite, isinf:</b> Devuelve un array booleano indicando si el valor es finito o no.</li>
<li><b>cos, cosh, sin, sinh, tan, tanh:</b> Funciones trigonométricas.</li>
<li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh:</b> Funciones trigonométricas inversas.</li>
<li><b>logical_not:</b> Inverso booleano de todos los valores del array (equivalente a -(array)).</li>
</ul>

Algunos ejemplos:

In [2]:
array = np.random.randn(2, 5)

print("array:\n",array, "\n")

print("valor absoluto:\n", np.abs(array), "\n")
print("raiz cuadrada:\n", np.sqrt(array), "\n")
print("exponencial:\n", np.exp(array), "\n")
print("logaritmo natural:\n", np.log(array), "\n")
print("floor:\n", np.floor(array), "\n")
print("ceil:\n", np.ceil(array), "\n")
print("valores nan:\n", np.isnan(np.sqrt(array)), "\n")

array:
 [[ 0.47473009  0.43434901 -0.47008638  1.64983988 -0.05821821]
 [-0.85331865 -0.82291134  0.08619     1.80870411  0.82138202]] 

valor absoluto:
 [[0.47473009 0.43434901 0.47008638 1.64983988 0.05821821]
 [0.85331865 0.82291134 0.08619    1.80870411 0.82138202]] 

raiz cuadrada:
 [[0.6890066  0.6590516         nan 1.28446093        nan]
 [       nan        nan 0.29358133 1.3448807  0.90630129]] 

exponencial:
 [[1.60758024 1.54395763 0.62494828 5.20614613 0.94344405]
 [0.42599884 0.43915127 1.09001341 6.10253407 2.27363989]] 

logaritmo natural:
 [[-0.74500886 -0.83390689         nan  0.50067824         nan]
 [        nan         nan -2.45120116  0.59261063 -0.19676697]] 

floor:
 [[ 0.  0. -1.  1. -1.]
 [-1. -1.  0.  1.  0.]] 

ceil:
 [[ 1.  1. -0.  2. -0.]
 [-0. -0.  1.  2.  1.]] 

valores nan:
 [[False False  True False  True]
 [ True  True False False False]] 



#### Funciones binarias

Son aquellas funciones que reciben como parámetro dos arrays.
<ul>
<li><b>add:</b> Adición de los elementos de los dos arrays (equivalente a array1 + array2).</li>
<li><b>subtract:</b> Resta de los elementos de los dos arrays (equivalente a array1 - array2).</li>
<li><b>multiply:</b> Multiplica los elementos de los dos arrays (equivalente a array1 \* array2).</li>
<li><b>divide, floor_divide:</b> Divide los elementos de los dos arrays (equivalente a array1 / (o //) array2).</li>
<li><b>power:</b> Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2).</li>
<li><b>maximum, fmax:</b> Calcula el máximo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>minimum, fmin:</b> Calcula el mínimo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>mod:</b> Calcula el resto de la división de los dos arrays (equivalente a array1 % array2).</li>
<li><b>greater, greater_equal, less, less_equal, equal, not_equal:</b> Comparativas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
<li><b>logical_and, logical_or, logical_xor:</b> Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
</ul>

Algunos ejemplos:

In [3]:
array1 = np.random.random_integers(10, size=(2,5))
array2 = np.random.random_integers(10, size=(2,5))

print("array1:\n",array1, "\n")
print("array2:\n",array2, "\n")

print("suma:\n", np.add(array1,array2), "\n")
print("resta:\n", np.subtract(array1,array2), "\n")
print("multiplicación:\n", np.multiply(array1,array2), "\n")
print("división:\n", np.divide(array1,array2), "\n")
print("potencia:\n", np.power(array1,array2), "\n")
print("máximo:\n", np.maximum(array1,array2), "\n")
print("mayor que:\n", np.greater(array1,array2), "\n")

array1:
 [[10  5 10  1  5]
 [ 9  8  7  6  7]] 

array2:
 [[ 8  2  1  3  9]
 [10 10  9  8  8]] 

suma:
 [[18  7 11  4 14]
 [19 18 16 14 15]] 

resta:
 [[ 2  3  9 -2 -4]
 [-1 -2 -2 -2 -1]] 

multiplicación:
 [[80 10 10  3 45]
 [90 80 63 48 56]] 

división:
 [[ 1.25        2.5        10.          0.33333333  0.55555556]
 [ 0.9         0.8         0.77777778  0.75        0.875     ]] 

potencia:
 [[ 100000000         25         10          1    1953125]
 [-808182895 1073741824   40353607    1679616    5764801]] 

máximo:
 [[10  5 10  3  9]
 [10 10  9  8  8]] 

mayor que:
 [[ True  True  True False False]
 [False False False False False]] 



### Selección de elementos de ndarrays en función de una condición

NumPy pone a nuestra disposición, a través de la función <b>np.where</b> la posibilidad de generar un array de salida a partir de dos de entrada, estableciendo una máscara booleana que indique si (elemento a elemento) debemos enviar a la salida el elemento del primer ndarray (valor True) o del segundo (valor False).

In [4]:
array1 = np.random.randn(5,5)
array2 = np.random.randn(5, 5)

print("array1:\n",array1,"\n")
print("array2:\n",array2)

print("\nFusión condicional:")
print(np.where(array1 < array2, array1, array2))

print("\nAnidación de condiciones:")
print(np.where(array1 < array2, np.where(array1 < 0, 0, array1), array2))

array1:
 [[ 0.39150748  1.19082025  0.76003585  0.99326895 -0.31093908]
 [-0.56410891  0.53625579  0.99610461 -1.37209786  1.51852779]
 [ 0.51493705 -2.13972558 -0.11255468 -1.0288628   0.19744574]
 [ 0.48587151  1.82301345 -0.81473429 -1.69619484  0.42173404]
 [-0.54514625 -0.7794695   0.73314936 -0.81449584  0.13287491]] 

array2:
 [[-0.76830128  0.24593779 -0.06489364 -0.96385221 -1.17342045]
 [-0.28124252  0.13669577  0.40818803  1.58064807 -1.06977363]
 [-0.88147426  1.1937555  -0.57533986 -0.1091667  -0.05841226]
 [-0.6142396   0.3057124  -0.30461161  0.24864876 -0.05146942]
 [-2.01418544  0.39585475  0.07258669 -1.1785516  -1.29077304]]

Fusión condicional:
[[-0.76830128  0.24593779 -0.06489364 -0.96385221 -1.17342045]
 [-0.56410891  0.13669577  0.40818803 -1.37209786 -1.06977363]
 [-0.88147426 -2.13972558 -0.57533986 -1.0288628  -0.05841226]
 [-0.6142396   0.3057124  -0.81473429 -1.69619484 -0.05146942]
 [-2.01418544 -0.7794695   0.07258669 -1.1785516  -1.29077304]]

Anidación 

### Funciones matemáticas y estadísticas

NumPy ofrece un amplio conjunto de funciones matemáticas y estadísticas que se pueden aplicar sobre ndarrays. A continuación se pueden encontrar los ejemplos más típicos (hay algunas más que pueden consultarse en la documentación oficial de NumPy).<br/>
<ul>
<li><b>sum:</b> Suma de elementos.</li>
<li><b>mean:</b> Media aritmética de los elementos.</li>
<li><b>median:</b> Mediana de los elementos.</li>
<li><b>std:</b> Desviación estándar de los elementos.</li>
<li><b>var:</b> Varianza de los elementos.</li>
<li><b>min:</b> Valor mínimo de los elementos.</li>
<li><b>max:</b> Valor máximo de los elementos.</li>
<li><b>argmin:</b> Índice del valor mínimo.</li>
<li><b>argmax:</b> Índice del valor máximo.</li>
<li><b>cumsum:</b> Suma acumulada de los elementos.</li>
<li><b>cumprod:</b> Producto acumulado de los elementos.</li>
</ul>

Todas estas funciones pueden recibir, además del ndarray sobre el que se aplicarán, un segundo parámetro llamado <b>axis</b>. Si no se recibe este parámetro las funciones se aplicarán sobre el conjunto global de los elementos del ndarray, pero si se incluye, podrá tomar dos valores:
<ul>
<li>Valor 0: Aplicará la función por columnas</li>
<li>Valor 1: Aplicará la función por filas</li>

In [5]:
array = np.random.randn(5,4)

print("array:\n",array,"\n")

print("\nOperación global:")
print(np.sum(array))

print("\nOperación por columnas:")
print(np.sum(array, 0))

print("\nOperación por filas:")
print(np.sum(array, 1))

array:
 [[ 0.50755632 -1.91018437 -0.02955838  0.68621255]
 [-0.80116621 -0.03369039  0.04391612  1.57825501]
 [ 1.29650882  0.65253235  1.18728301  0.75872761]
 [ 0.34912863  1.96896773  1.75912913  0.35549432]
 [-0.80921978  0.87408354 -0.0053615  -1.51895441]] 


Operación global:
6.909660102830624

Operación por columnas:
[0.54280779 1.55170886 2.95540838 1.85973508]

Operación por filas:
[-0.74597389  0.78731453  3.8950518   4.43271981 -1.45945215]


Adicionalmente algunas de estas funciones pueden ser utilizadas como "métodos" de los ndarray y no sólo como funciones sobre los mismos. En este caso la sintáxis cambiará y se utilizará la notación "ndarray.funcion()" 

In [6]:
print(array.sum())
print(array.sum(0))
print(array.sum(1))

6.909660102830624
[0.54280779 1.55170886 2.95540838 1.85973508]
[-0.74597389  0.78731453  3.8950518   4.43271981 -1.45945215]


### Operaciones sobre ndarrays booleanos

Dado que, internamente, Python trata los valores booleanos True como 1 y los False como 0, es muy sencillo realizar operaciones matemáticas sobre estos valores booleanos de forma que se puedan hacer diferentes chequeos. Por ejemplo...

In [7]:
array = np.random.randn(5,5)

print("array:\n",array,"\n")

print("\nElementos mayores que 0")
print((array>0).sum())

print("\nElementos menores que la media")
print((array < array.mean()).sum())


array:
 [[ 0.65254479  0.80715418  0.73314873 -0.25536637 -1.59689709]
 [ 1.21287635  1.33941193  0.06110765  0.35856212 -1.20289598]
 [-2.41533642 -0.52319384  1.05351272  1.3134208  -0.6650845 ]
 [ 0.3462053   0.16537632  0.1324861   0.59529329 -0.51133136]
 [ 0.17204377 -0.54745118  0.67123536 -1.30636505 -1.05297246]] 


Elementos mayores que 0
15

Elementos menores que la media
10


NumPy también pone a nuestra disposición dos funciones de chequeo predefinidas sobre ndarrays booleanos:<br/>
<ul>
<li><b>any:</b> Para comprobar si alguno de los elementos es True.</li>
<li><b>all:</b> Para comprobar si todos los elementos son True.</li>
</ul>

In [8]:
print("Alguno de los elementos es igual a 0")
print((array==0).any())

print("\nTodos los elementos son menores que 0")
print((array<0).all())

print("\nTodos los elementos entan en un rango")
print( ((array >= -2) & (array <=2)).all() )

Alguno de los elementos es igual a 0
False

Todos los elementos son menores que 0
False

Todos los elementos entan en un rango
False


### Ordenación de ndarrays

In [9]:
array = np.random.randint(10,size=(2,5))
print("array:\n",array)

print("\nDatos ordenados")
print(np.sort(array)) # sort along the last axis

print("\nDatos ordenados según el primer eje")
print(np.sort(array, axis=0)) # sort along the first axis

print("\nDatos ordenados de forma unidimensional")
print(np.sort(array, axis=None)) # sort the flattened array


array:
 [[0 8 3 5 5]
 [4 3 9 9 2]]

Datos ordenados
[[0 3 5 5 8]
 [2 3 4 9 9]]

Datos ordenados según el primer eje
[[0 3 3 5 2]
 [4 8 9 9 5]]

Datos ordenados de forma unidimensional
[0 2 3 3 4 5 5 8 9 9]


### Funciones de conjunto

NumPy permite realizar tratamientos sobre un ndarray asumiendo que el total de los elementos del mismo forman un conjunto.<br/>
<ul>
<li><b>unique:</b> Calcula el conjunto único de elementos sin duplicados.</li>
<li><b>intersect1d:</b> Calcula la intersección de los elementos de dos arrays.</li>
<li><b>union1d:</b> Calcula la unión de los elementos de dos arays.</li>
<li><b>in1d:</b> Calcula un array booleano que indica si cada elemento del primer array está contenido en el segundo.</li>
<li><b>setdiff1d:</b> Calcula la diferencia entre ambos conjuntos.</li>
<li><b>setxor1d:</b> Calcula la diferencia simétrica entre ambos conjuntos.</li>
</ul>

In [10]:
array1 = np.array([6, 0, 0, 0, 3, 2, 5, 6])
array2 = np.array([7, 4, 3, 1, 2, 6, 5])

print("conjunto único array1:", np.unique(array1))
print("intersección:", np.intersect1d(array1,array2))
print("unión:", np.union1d(array1,array2))
print("está contenido en:", np.in1d(array1,array2))
print("elementos del primer array no contenidos en el segundo", np.setdiff1d(array1,array2))
print("diferencia simétrica:", np.setxor1d(array1,array2))

conjunto único array1: [0 2 3 5 6]
intersección: [2 3 5 6]
unión: [0 1 2 3 4 5 6 7]
está contenido en: [ True False False False  True  True  True  True]
elementos del primer array no contenidos en el segundo [0]
diferencia simétrica: [0 1 4 7]
