# Operaciones sobre ndarrays

NumPy pone a nuestra disposición un amplio conjunto de funciones optimizadas para aplicar sobre ndarrays de forma global evitando así la necesidad de utilizar bucles (mucho más costosos).

In [23]:
import numpy as np

### Operaciones elemento a elemento - Universal functions

El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas "funciones universales" (o ufuncs) que permiten la realización de operaciones elemento a elemento de un array. En función del número de parámetros encontramos dos tipos de funciones universales.

#### Funciones unarias

Son aquellas funciones que reciben como parámetro un único ndarray.<br/>
<ul>
<li><b>abs, fabs:</b> Valor absoluto.</li>
<li><b>sqrt:</b> Raíz cuadrada (equivalente a array \*\* 0.5).</li>
<li><b>square:</b> Potencia al cuadrado (equivalente a array ** 2).</li>
<li><b>exp:</b> Potencia de e.</li>
<li><b>log, log10, log2, log1p:</b> Logaritmos en distintas bases.</li>
<li><b>sign:</b> Signo (+ = 1 / - = -1 / 0 = 0).</li>
<li><b>ceil:</b> Techo.</li>
<li><b>floor:</b> Suelo.</li>
<li><b>rint:</b> Redondeo al entero más cercano.</li>
<li><b>modf:</b> Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.</li>
<li><b>isnan:</b> Devuelve un array booleano indicando si el valor es NaN o no.</li>
<li><b>isfinite, isinf:</b> Devuelve un array booleano indicando si el valor es finito o no.</li>
<li><b>cos, cosh, sin, sinh, tan, tanh:</b> Funciones trigonométricas.</li>
<li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh:</b> Funciones trigonométricas inversas.</li>
<li><b>logical_not:</b> Inverso booleano de todos los valores del array (equivalente a -(array)).</li>
</ul>

Algunos ejemplos:

In [25]:
array = np.random.randn(5, 5)

print("array\n:",array, "\n")

print("valor absoluto:\n", np.abs(array))
print("raiz cuadrada:\n", np.sqrt(array))
print("exponencial:\n", np.exp(array))
print("logaritmo natural:\n", np.log(array))
print("floor:\n", np.floor(array))
print("ceil:\n", np.ceil(array))



array
: [[ 0.02833597  0.90444496 -0.19207427 -1.83674983 -0.0399558 ]
 [-0.3612924   1.62929074 -0.74209782  2.29010934 -0.52012446]
 [ 0.3219781   1.2163776   0.61021882 -1.02944346  1.32957398]
 [-0.46632415 -0.05633291  0.45710338  0.09792089  2.07244967]
 [ 0.19864355  0.39999263  0.71737042 -0.65119638  0.59364401]] 

valor absoluto:
 [[0.02833597 0.90444496 0.19207427 1.83674983 0.0399558 ]
 [0.3612924  1.62929074 0.74209782 2.29010934 0.52012446]
 [0.3219781  1.2163776  0.61021882 1.02944346 1.32957398]
 [0.46632415 0.05633291 0.45710338 0.09792089 2.07244967]
 [0.19864355 0.39999263 0.71737042 0.65119638 0.59364401]]
raiz cuadrada:
 [[0.16833293 0.95102311        nan        nan        nan]
 [       nan 1.27643674        nan 1.51331072        nan]
 [0.56743114 1.1028951  0.78116504        nan 1.15307154]
 [       nan        nan 0.67609421 0.31292313 1.43960053]
 [0.44569445 0.6324497  0.84697722        nan 0.77048297]]
exponencial:
 [[1.02874126 2.47056028 0.82524558 0.15933445

<ipython-input-25-26ffd28f1de1>:6: RuntimeWarning: invalid value encountered in sqrt
  print("raiz cuadrada:\n", np.sqrt(array))
<ipython-input-25-26ffd28f1de1>:8: RuntimeWarning: invalid value encountered in log
  print("logaritmo natural:\n", np.log(array))


#### Funciones binarias

Son aquellas funciones que reciben como parámetro dos arrays.
<ul>
<li><b>add:</b> Adición de los elementos de los dos arrays (equivalente a array1 + array2).</li>
<li><b>subtract:</b> Resta de los elementos de los dos arrays (equivalente a array1 - array2).</li>
<li><b>multiply:</b> Multiplica los elementos de los dos arrays (equivalente a array1 \* array2).</li>
<li><b>divide, floor_divide:</b> Divide los elementos de los dos arrays (equivalente a array1 / (o //) array2).</li>
<li><b>power:</b> Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2).</li>
<li><b>maximum, fmax:</b> Calcula el máximo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>minimum, fmin:</b> Calcula el mínimo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>mod:</b> Calcula el resto de la división de los dos arrays (equivalente a array1 % array2).</li>
<li><b>greater, greater_equal, less, less_equal, equal, not_equal:</b> Comparativas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
<li><b>logical_and, logical_or, logical_xor:</b> Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
</ul>