# Operaciones sobre ndarrays

NumPy pone a nuestra disposición un amplio conjunto de funciones optimizadas para aplicar sobre ndarrays de forma global evitando así la necesidad de utilizar bucles (mucho más costosos).

In [2]:
import numpy as np

import warnings; warnings.simplefilter('ignore')

### Operaciones elemento a elemento - Universal functions

El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas "funciones universales" (o ufuncs) que permiten la realización de operaciones elemento a elemento de un array. En función del número de parámetros encontramos dos tipos de funciones universales.

#### Funciones unarias

Son aquellas funciones que reciben como parámetro un único ndarray.<br/>
<ul>
<li><b>abs, fabs:</b> Valor absoluto.</li>
<li><b>sqrt:</b> Raíz cuadrada (equivalente a array \*\* 0.5).</li>
<li><b>square:</b> Potencia al cuadrado (equivalente a array ** 2).</li>
<li><b>exp:</b> Potencia de e.</li>
<li><b>log, log10, log2, log1p:</b> Logaritmos en distintas bases.</li>
<li><b>sign:</b> Signo (+ = 1 / - = -1 / 0 = 0).</li>
<li><b>ceil:</b> Techo.</li>
<li><b>floor:</b> Suelo.</li>
<li><b>rint:</b> Redondeo al entero más cercano.</li>
<li><b>modf:</b> Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.</li>
<li><b>isnan:</b> Devuelve un array booleano indicando si el valor es NaN o no.</li>
<li><b>isfinite, isinf:</b> Devuelve un array booleano indicando si el valor es finito o no.</li>
<li><b>cos, cosh, sin, sinh, tan, tanh:</b> Funciones trigonométricas.</li>
<li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh:</b> Funciones trigonométricas inversas.</li>
<li><b>logical_not:</b> Inverso booleano de todos los valores del array (equivalente a -(array)).</li>
</ul>

Algunos ejemplos:

In [17]:
array = np.random.randn(2, 5)

print("array:\n",array, "\n")

print("valor absoluto:\n", np.abs(array), "\n")
print("raiz cuadrada:\n", np.sqrt(array), "\n")
print("exponencial:\n", np.exp(array), "\n")
print("logaritmo natural:\n", np.log(array), "\n")
print("floor:\n", np.floor(array), "\n")
print("ceil:\n", np.ceil(array), "\n")
print("valores nan:\n", np.isnan(np.sqrt(array)), "\n")

array:
 [[-0.83010854 -1.71173545  0.26769221 -0.07556916  0.37250466]
 [-0.06096563 -0.86027395  0.00928673 -0.60242059  0.86162577]] 

valor absoluto:
 [[0.83010854 1.71173545 0.26769221 0.07556916 0.37250466]
 [0.06096563 0.86027395 0.00928673 0.60242059 0.86162577]] 

raiz cuadrada:
 [[       nan        nan 0.5173898         nan 0.6103316 ]
 [       nan        nan 0.09636767        nan 0.92823799]] 

exponencial:
 [[0.43600196 0.18055218 1.30694481 0.9272156  1.45136525]
 [0.94085558 0.42304617 1.00932998 0.54748479 2.36700576]] 

logaritmo natural:
 [[        nan         nan -1.31791743         nan -0.98750572]
 [        nan         nan -4.67916905         nan -0.14893425]] 

floor:
 [[-1. -2.  0. -1.  0.]
 [-1. -1.  0. -1.  0.]] 

ceil:
 [[-0. -1.  1. -0.  1.]
 [-0. -0.  1. -0.  1.]] 

valores nan:
 [[ True  True False  True False]
 [ True  True False  True False]] 



#### Funciones binarias

Son aquellas funciones que reciben como parámetro dos arrays.
<ul>
<li><b>add:</b> Adición de los elementos de los dos arrays (equivalente a array1 + array2).</li>
<li><b>subtract:</b> Resta de los elementos de los dos arrays (equivalente a array1 - array2).</li>
<li><b>multiply:</b> Multiplica los elementos de los dos arrays (equivalente a array1 \* array2).</li>
<li><b>divide, floor_divide:</b> Divide los elementos de los dos arrays (equivalente a array1 / (o //) array2).</li>
<li><b>power:</b> Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2).</li>
<li><b>maximum, fmax:</b> Calcula el máximo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>minimum, fmin:</b> Calcula el mínimo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>mod:</b> Calcula el resto de la división de los dos arrays (equivalente a array1 % array2).</li>
<li><b>greater, greater_equal, less, less_equal, equal, not_equal:</b> Comparativas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
<li><b>logical_and, logical_or, logical_xor:</b> Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
</ul>

Algunos ejemplos:

In [30]:
array1 = np.random.random_integers(10, size=(2,5))
array2 = np.random.random_integers(10, size=(2,5))

print("array1:\n",array1, "\n")
print("array2:\n",array2, "\n")

print("suma:\n", np.add(array1,array2), "\n")
print("resta:\n", np.subtract(array1,array2), "\n")
print("multiplicación:\n", np.multiply(array1,array2), "\n")
print("división:\n", np.divide(array1,array2), "\n")
print("potencia:\n", np.power(array1,array2), "\n")
print("máximo:\n", np.maximum(array1,array2), "\n")
print("mayor que:\n", np.greater(array1,array2), "\n")

array1:
 [[10  7  4  5  7]
 [ 6 10  4  8  6]] 

array2:
 [[3 2 6 4 2]
 [2 7 4 2 3]] 

suma:
 [[13  9 10  9  9]
 [ 8 17  8 10  9]] 

resta:
 [[ 7  5 -2  1  5]
 [ 4  3  0  6  3]] 

multiplicación:
 [[30 14 24 20 14]
 [12 70 16 16 18]] 

división:
 [[3.33333333 3.5        0.66666667 1.25       3.5       ]
 [3.         1.42857143 1.         4.         2.        ]] 

potencia:
 [[    1000       49     4096      625       49]
 [      36 10000000      256       64      216]] 

máximo:
 [[10  7  6  5  7]
 [ 6 10  4  8  6]] 

mayor que:
 [[ True  True False  True  True]
 [ True  True False  True  True]] 



### Selección de elementos de ndarrays en función de una condición

NumPy pone a nuestra disposición, a través de la función <b>np.where</b> la posibilidad de generar un array de salida a partir de dos de entrada, estableciendo una máscara booleana que indique si (elemento a elemento) debemos enviar a la salida el elemento del primer ndarray (valor True) o del segundo (valor False).

In [21]:
array1 = np.random.randn(5,5)
array2 = np.random.randn(5, 5)

print("array1:\n",array1,"\n")
print("array2:\n",array2)

print("\nFusión condicional:")
print(np.where(array1 < array2, array1, array2))

print("\nAnidación de condiciones:")
print(np.where(array1 < array2, np.where(array1 < 0, 0, array1), array2))

array1:
 [[-2.44300905  0.77921415 -2.11836417 -0.11472166 -1.39955176]
 [ 0.61779811  1.18228571 -1.48151924  0.15422247 -0.70997297]
 [-1.0070794  -0.08036695 -1.43970586  1.4640655  -0.45552624]
 [-1.06350232  0.49541124 -2.03316739  1.10058493  1.37322856]
 [-0.24661262 -0.21065946 -0.57705948 -1.48159245 -1.68244194]] 

array2:
 [[-0.66408712  0.14226306 -0.28062698 -2.98624159 -0.51936066]
 [ 2.53668692  0.99235238 -0.16422853  0.54860607 -0.57097116]
 [ 0.8918802  -1.44576066  1.60439321  0.38364186  0.75680777]
 [ 0.68879798  1.51898573  2.01468837 -0.34538455  0.43954907]
 [ 1.143037   -0.57647781 -0.23215485  0.42383913 -0.29335377]]

Fusión condicional:
[[-2.44300905  0.14226306 -2.11836417 -2.98624159 -1.39955176]
 [ 0.61779811  0.99235238 -1.48151924  0.15422247 -0.70997297]
 [-1.0070794  -1.44576066 -1.43970586  0.38364186 -0.45552624]
 [-1.06350232  0.49541124 -2.03316739 -0.34538455  0.43954907]
 [-0.24661262 -0.57647781 -0.57705948 -1.48159245 -1.68244194]]

Anidación 

### Funciones matemáticas y estadísticas

NumPy ofrece un amplio conjunto de funciones matemáticas y estadísticas que se pueden aplicar sobre ndarrays. A continuación se pueden encontrar los ejemplos más típicos (hay algunas más que pueden consultarse en la documentación oficial de NumPy).<br/>
<ul>
<li><b>sum:</b> Suma de elementos.</li>
<li><b>mean:</b> Media aritmética de los elementos.</li>
<li><b>median:</b> Mediana de los elementos.</li>
<li><b>std:</b> Desviación estándar de los elementos.</li>
<li><b>var:</b> Varianza de los elementos.</li>
<li><b>min:</b> Valor mínimo de los elementos.</li>
<li><b>max:</b> Valor máximo de los elementos.</li>
<li><b>argmin:</b> Índice del valor mínimo.</li>
<li><b>argmax:</b> Índice del valor máximo.</li>
<li><b>cumsum:</b> Suma acumulada de los elementos.</li>
<li><b>cumprod:</b> Producto acumulado de los elementos.</li>
</ul>

Todas estas funciones pueden recibir, además del ndarray sobre el que se aplicarán, un segundo parámetro llamado <b>axis</b>. Si no se recibe este parámetro las funciones se aplicarán sobre el conjunto global de los elementos del ndarray, pero si se incluye, podrá tomar dos valores:
<ul>
<li>Valor 0: Aplicará la función por columnas</li>
<li>Valor 1: Aplicará la función por filas</li>

In [29]:
array = np.random.randn(5,4)

print("array:\n",array,"\n")

print("\nOperación global:")
print(np.sum(array))

print("\nOperación por columnas:")
print(np.sum(array, 0))

print("\nOperación por filas:")
print(np.sum(array, 1))

array:
 [[-0.03274941  0.51626784 -2.81096539  0.07424415]
 [ 0.68255449  0.17562898  0.79973098  0.85128752]
 [-1.48787746 -0.86540333  0.68436982  0.28771631]
 [ 1.00617917 -0.3595035   0.1167053   1.32272646]
 [ 0.02230578 -0.67355735  2.73776853 -1.06007977]] 


Operación global:
1.987349117812156

Operación por columnas:
[ 0.19041256 -1.20656736  1.52760924  1.47589468]

Operación por filas:
[-2.25320282  2.50920197 -1.38119466  2.08610744  1.02643719]


Adicionalmente algunas de estas funciones pueden ser utilizadas como "métodos" de los ndarray y no sólo como funciones sobre los mismos. En este caso la sintáxis cambiará y se utilizará la notación "ndarray.funcion()" 

In [34]:
print(array.sum())
print(array.sum(0))
print(array.sum(1))

1.987349117812156
[ 0.19041256 -1.20656736  1.52760924  1.47589468]
[-2.25320282  2.50920197 -1.38119466  2.08610744  1.02643719]


### Operaciones sobre ndarrays booleanos

Dado que, internamente, Python trata los valores booleanos True como 1 y los False como 0, es muy sencillo realizar operaciones matemáticas sobre estos valores booleanos de forma que se puedan hacer diferentes chequeos. Por ejemplo...

In [55]:
array = np.random.randn(5,5)

print("array:\n",array,"\n")

print("\nElementos mayores que 0")
print((array>0).sum())

print("\nElementos menores que la media")
print((array < array.mean()).sum())


array:
 [[-0.09028405  1.20404426  0.17019342  0.15661857  0.43965323]
 [-1.09253296  0.26262647  0.06034484  0.36498415  1.25776417]
 [ 1.31684065  1.39522041 -0.36350749  0.10933203  0.22879655]
 [ 0.84657443 -0.55255485 -0.44360896 -0.84085451  1.16261577]
 [ 0.04463715  0.94913871  0.93484431  0.40765312  0.23061015]] 


Elementos mayores que 0
19

Elementos menores que la media
14


NumPy también pone a nuestra disposición dos funciones de chequeo predefinidas sobre ndarrays booleanos:<br/>
<ul>
<li><b>any:</b> Para comprobar si alguno de los elementos es True.</li>
<li><b>all:</b> Para comprobar si todos los elementos son True.</li>
</ul>

In [57]:
print("Alguno de los elementos es igual a 0")
print((array==0).any())

print("\nTodos los elementos son menores que 0")
print((array<0).all())

print("\nTodos los elementos entan en un rango")
print( ((array >= -2) & (array <=2)).all() )

Alguno de los elementos es igual a 0
False

Todos los elementos son menores que 0
False

Todos los elementos entan en un rango
True


### Ordenación de ndarrays

In [76]:
array = np.random.randint(10,size=(2,5))
print("array:\n",array)

print("\nDatos ordenados")
print(np.sort(array)) # sort along the last axis

print("\nDatos ordenados según el primer eje")
print(np.sort(array, axis=0)) # sort along the first axis

print("\nDatos ordenados de forma unidimensional")
print(np.sort(array, axis=None)) # sort the flattened array


array:
 [[5 8 8 5 7]
 [7 1 0 0 9]]

Datos ordenados
[[5 5 7 8 8]
 [0 0 1 7 9]]

Datos ordenados según el primer eje
[[5 1 0 0 7]
 [7 8 8 5 9]]

Datos ordenados de forma unidimensional
[0 0 1 5 5 7 7 8 8 9]


### Funciones de conjunto

NumPy permite realizar tratamientos sobre un ndarray asumiendo que el total de los elementos del mismo forman un conjunto.<br/>
<ul>
<li><b>unique:</b> Calcula el conjunto único de elementos sin duplicados.</li>
<li><b>intersect1d:</b> Calcula la intersección de los elementos de dos arrays.</li>
<li><b>union1d:</b> Calcula la unión de los elementos de dos arays.</li>
<li><b>in1d:</b> Calcula un array booleano que indica si cada elemento del primer array está contenido en el segundo.</li>
<li><b>setdiff1d:</b> Calcula la diferencia entre ambos conjuntos.</li>
<li><b>setxor1d:</b> Calcula la diferencia simétrica entre ambos conjuntos.</li>
</ul>

In [92]:
array1 = np.array([6, 0, 0, 0, 3, 2, 5, 6])
array2 = np.array([7, 4, 3, 1, 2, 6, 5])

print("conjunto único array1:", np.unique(array1))
print("intersección:", np.intersect1d(array1,array2))
print("unión:", np.union1d(array1,array2))
print("está contenido en:", np.in1d(array1,array2))
print("elementos del primer array no contenidos en el segundo", np.setdiff1d(array1,array2))
print("diferencia simétrica":, np.setxor1d(array1,array2))

conjunto único array1: [0 2 3 5 6]
intersección: [2 3 5 6]
unión: [0 1 2 3 4 5 6 7]
está contenido en: [ True False False False  True  True  True  True]
elementos del primer array no contenidos en el segundo [0]
[0 1 4 7]
