# Operaciones sobre ndarrays

NumPy pone a nuestra disposición un amplio conjunto de funciones optimizadas para aplicar sobre ndarrays de forma global evitando así la necesidad de utilizar bucles (mucho más costosos).

In [28]:
import numpy as np

import warnings; warnings.simplefilter('ignore')

### Operaciones elemento a elemento - Universal functions

El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas "funciones universales" (o ufuncs) que permiten la realización de operaciones elemento a elemento de un array. En función del número de parámetros encontramos dos tipos de funciones universales.

#### Funciones unarias

Son aquellas funciones que reciben como parámetro un único ndarray.<br/>
<ul>
<li><b>abs, fabs:</b> Valor absoluto.</li>
<li><b>sqrt:</b> Raíz cuadrada (equivalente a array \*\* 0.5).</li>
<li><b>square:</b> Potencia al cuadrado (equivalente a array ** 2).</li>
<li><b>exp:</b> Potencia de e.</li>
<li><b>log, log10, log2, log1p:</b> Logaritmos en distintas bases.</li>
<li><b>sign:</b> Signo (+ = 1 / - = -1 / 0 = 0).</li>
<li><b>ceil:</b> Techo.</li>
<li><b>floor:</b> Suelo.</li>
<li><b>rint:</b> Redondeo al entero más cercano.</li>
<li><b>modf:</b> Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.</li>
<li><b>isnan:</b> Devuelve un array booleano indicando si el valor es NaN o no.</li>
<li><b>isfinite, isinf:</b> Devuelve un array booleano indicando si el valor es finito o no.</li>
<li><b>cos, cosh, sin, sinh, tan, tanh:</b> Funciones trigonométricas.</li>
<li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh:</b> Funciones trigonométricas inversas.</li>
<li><b>logical_not:</b> Inverso booleano de todos los valores del array (equivalente a -(array)).</li>
</ul>

Algunos ejemplos:

In [17]:
array = np.random.randn(2, 5)

print("array:\n",array, "\n")

print("valor absoluto:\n", np.abs(array), "\n")
print("raiz cuadrada:\n", np.sqrt(array), "\n")
print("exponencial:\n", np.exp(array), "\n")
print("logaritmo natural:\n", np.log(array), "\n")
print("floor:\n", np.floor(array), "\n")
print("ceil:\n", np.ceil(array), "\n")
print("valores nan:\n", np.isnan(np.sqrt(array)), "\n")

array:
 [[-0.83010854 -1.71173545  0.26769221 -0.07556916  0.37250466]
 [-0.06096563 -0.86027395  0.00928673 -0.60242059  0.86162577]] 

valor absoluto:
 [[0.83010854 1.71173545 0.26769221 0.07556916 0.37250466]
 [0.06096563 0.86027395 0.00928673 0.60242059 0.86162577]] 

raiz cuadrada:
 [[       nan        nan 0.5173898         nan 0.6103316 ]
 [       nan        nan 0.09636767        nan 0.92823799]] 

exponencial:
 [[0.43600196 0.18055218 1.30694481 0.9272156  1.45136525]
 [0.94085558 0.42304617 1.00932998 0.54748479 2.36700576]] 

logaritmo natural:
 [[        nan         nan -1.31791743         nan -0.98750572]
 [        nan         nan -4.67916905         nan -0.14893425]] 

floor:
 [[-1. -2.  0. -1.  0.]
 [-1. -1.  0. -1.  0.]] 

ceil:
 [[-0. -1.  1. -0.  1.]
 [-0. -0.  1. -0.  1.]] 

valores nan:
 [[ True  True False  True False]
 [ True  True False  True False]] 



#### Funciones binarias

Son aquellas funciones que reciben como parámetro dos arrays.
<ul>
<li><b>add:</b> Adición de los elementos de los dos arrays (equivalente a array1 + array2).</li>
<li><b>subtract:</b> Resta de los elementos de los dos arrays (equivalente a array1 - array2).</li>
<li><b>multiply:</b> Multiplica los elementos de los dos arrays (equivalente a array1 \* array2).</li>
<li><b>divide, floor_divide:</b> Divide los elementos de los dos arrays (equivalente a array1 / (o //) array2).</li>
<li><b>power:</b> Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2).</li>
<li><b>maximum, fmax:</b> Calcula el máximo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>minimum, fmin:</b> Calcula el mínimo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>mod:</b> Calcula el resto de la división de los dos arrays (equivalente a array1 % array2).</li>
<li><b>greater, greater_equal, less, less_equal, equal, not_equal:</b> Comparativas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
<li><b>logical_and, logical_or, logical_xor:</b> Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
</ul>

Algunos ejemplos:

In [30]:
array1 = np.random.random_integers(10, size=(2,5))
array2 = np.random.random_integers(10, size=(2,5))

print("array1:\n",array1, "\n")
print("array2:\n",array2, "\n")

print("suma:\n", np.add(array1,array2), "\n")
print("resta:\n", np.subtract(array1,array2), "\n")
print("multiplicación:\n", np.multiply(array1,array2), "\n")
print("división:\n", np.divide(array1,array2), "\n")
print("potencia:\n", np.power(array1,array2), "\n")
print("máximo:\n", np.maximum(array1,array2), "\n")
print("mayor que:\n", np.greater(array1,array2), "\n")

array1:
 [[10  7  4  5  7]
 [ 6 10  4  8  6]] 

array2:
 [[3 2 6 4 2]
 [2 7 4 2 3]] 

suma:
 [[13  9 10  9  9]
 [ 8 17  8 10  9]] 

resta:
 [[ 7  5 -2  1  5]
 [ 4  3  0  6  3]] 

multiplicación:
 [[30 14 24 20 14]
 [12 70 16 16 18]] 

división:
 [[3.33333333 3.5        0.66666667 1.25       3.5       ]
 [3.         1.42857143 1.         4.         2.        ]] 

potencia:
 [[    1000       49     4096      625       49]
 [      36 10000000      256       64      216]] 

máximo:
 [[10  7  6  5  7]
 [ 6 10  4  8  6]] 

mayor que:
 [[ True  True False  True  True]
 [ True  True False  True  True]] 



### Selección de elementos de ndarrays en función de una condición