# Álgebra lineal

Hasta el momento hemos visto cómo aplicar funciones "elemento a elemento" a matrices multidimensionales pero, en ningún caso, hemos aplicado funciones de cálculo matricial sobre las mismas. NumPy ofrece un amplio conjunto de funciones que permiten realizar multitud de tratamientos/operaciones matriciales. 

Algunas de las más comunes son:<br/>
<ul>
<li><b>diag:</b> Recupera la diagonal principal del ndarray pasado como parámetro.</li>
<li><b>dot:</b> Realiza el producto escalar de dos ndarray.</li>
<li><b>trace:</b> Calcula la suma de los elementos de la diagonal principal.</li>
<li><b>det:</b> Calcula el determinante de un ndarray.</li>
<li><b>eig:</b> Calcula los autovalores y autovectores de un ndarray.</li>
<li><b>inv:</b> Calcula la inversa de una matriz.</li>
<li><b>qr:</b> Calcula la descomposición QR de una matriz.</li>
<li><b>svd:</b> Calcula la descomposición de valores singulares (Singular Value Decomposition) de una matriz.</li>
<li><b>solve:</b> Calcula el resultado del sistema lineal Ax = B donde A y B son las matrices de entrada y x la salida.</li>
<li><b>lstsq:</b> Calcula la solución de mínimos cuadrados a y = Xb, donde y y b son los parámetros de entrada y X la salida.</li>
</ul>

In [57]:
import numpy as np
import numpy.linalg as linalg

In [40]:
array = np.random.randint(10, size=(3,3))
print("datos:\n", array)
print("\ndiagonal principal:",np.diag(array))
print("\ndiagonal por encima de la principal:",np.diag(array, k=1))
print("\ndiagonal por debajo de la principal:",np.diag(array, k=-1))

datos:
 [[3 4 9]
 [6 3 4]
 [6 8 1]]

diagonal principal: [3 3 1]

diagonal por encima de la principal: [4 4]

diagonal por debajo de la principal: [6 8]


In [54]:
array1 = np.random.randint(low=-4, high=10, size=(2,4))
array2 = np.random.randint(low=-3, high=1, size=(4,4))
print("datos1:\n", array1)
print("\ndatos2:\n", array2)

print("\nproducto escalar:\n", np.dot(array1,array2))

datos1:
 [[-1  2  9  1]
 [-4  4 -2  6]]

datos2:
 [[-1 -1 -3 -2]
 [-3 -2 -1  0]
 [-3 -1 -3 -2]
 [-3 -3  0  0]]

producto escalar:
 [[-35 -15 -26 -16]
 [-20 -20  14  12]]


In [65]:
array = np.random.randint(low=-2, high=10, size=(4,4))
print("datos:\n", array)
print("\nsuma de la diagonal principal:", np.trace(array))

print("\ndeterminante:", linalg.det(array))


datos:
 [[ 9  1  4  8]
 [ 7  1  5  4]
 [ 2  8  2  0]
 [ 2 -1 -2  0]]

suma de la diagonal principal: 12

determinante: 680.0000000000003


det: Calcula el determinante de un ndarray.
eig: Calcula los autovalores y autovectores de un ndarray.
inv: Calcula la inversa de una matriz.
qr: Calcula la descomposición QR de una matriz.
svd: Calcula la descomposición de valores singulares (Singular Value Decomposition) de una matriz.
solve: Calcula el resultado del sistema lineal Ax = B donde A y B son las matrices de entrada y x la salida.
lstsq: