# Álgebra lineal

Hasta el momento hemos visto cómo aplicar funciones "elemento a elemento" a matrices multidimensionales pero, en ningún caso, hemos aplicado funciones de cálculo matricial sobre las mismas. NumPy ofrece un amplio conjunto de funciones que permiten realizar multitud de tratamientos/operaciones matriciales. 

Algunas de las más comunes son:<br/>
<ul>
<li><b>diag:</b> Recupera la diagonal principal del ndarray pasado como parámetro.</li>
<li><b>dot:</b> Realiza el producto escalar de dos ndarray.</li>
<li><b>trace:</b> Calcula la suma de los elementos de la diagonal principal.</li>
<li><b>det:</b> Calcula el determinante de un ndarray.</li>
<li><b>eig:</b> Calcula los autovalores y autovectores de un ndarray.</li>
<li><b>inv:</b> Calcula la inversa de una matriz.</li>
<li><b>qr:</b> Calcula la descomposición QR de una matriz.</li>
<li><b>svd:</b> Calcula la descomposición de valores singulares (Singular Value Decomposition) de una matriz.</li>
<li><b>solve:</b> Calcula el resultado del sistema lineal Ax = B donde A y B son las matrices de entrada y x la salida.</li>
<li><b>lstsq:</b> Calcula la solución de mínimos cuadrados a y = Xb, donde y y b son los parámetros de entrada y X la salida.</li>
</ul>

In [1]:
import numpy as np
import numpy.linalg as linalg

In [2]:
array = np.random.randint(10, size=(3,3))
print("datos:\n", array)
print("\ndiagonal principal:",np.diag(array))
print("\ndiagonal por encima de la principal:",np.diag(array, k=1))
print("\ndiagonal por debajo de la principal:",np.diag(array, k=-1))

datos:
 [[4 8 3]
 [6 3 8]
 [5 1 3]]

diagonal principal: [4 3 3]

diagonal por encima de la principal: [8 8]

diagonal por debajo de la principal: [6 1]


In [54]:
array1 = np.random.randint(low=-4, high=10, size=(2,4))
array2 = np.random.randint(low=-3, high=1, size=(4,4))
print("datos1:\n", array1)
print("\ndatos2:\n", array2)

print("\nproducto escalar:\n", np.dot(array1,array2))

datos1:
 [[-1  2  9  1]
 [-4  4 -2  6]]

datos2:
 [[-1 -1 -3 -2]
 [-3 -2 -1  0]
 [-3 -1 -3 -2]
 [-3 -3  0  0]]

producto escalar:
 [[-35 -15 -26 -16]
 [-20 -20  14  12]]


In [65]:
array = np.random.randint(low=-2, high=10, size=(4,4))
print("datos:\n", array)

print("\nsuma de la diagonal principal:", np.trace(array))
print("\ndeterminante:", linalg.det(array))

datos:
 [[ 9  1  4  8]
 [ 7  1  5  4]
 [ 2  8  2  0]
 [ 2 -1 -2  0]]

suma de la diagonal principal: 12

determinante: 680.0000000000003


In [47]:
array = np.random.randint(low=0, high=6, size=(4,4))
print("datos:\n", array)

print("\nautovalores y autovectores:\n")
a = linalg.eig(array)
print(a[0])
print("\n",a[1])

print("\nmatriz inversa:")
print(linalg.inv(array))

datos:
 [[5 2 2 4]
 [1 5 2 0]
 [5 3 3 3]
 [3 0 1 0]]

autovalores y autovectores:

[10.16126088  4.25672744  0.43636679 -1.85435511]

 [[-0.5921429  -0.37619903 -0.29178393 -0.50733663]
 [-0.37489938  0.8674274  -0.32906445  0.09226813]
 [-0.67140531 -0.13426798  0.8967567  -0.06255095]
 [-0.24089865 -0.2966751   0.04905258  0.85450776]]

matriz inversa:
[[ 0.42857143  0.17142857 -0.57142857  0.51428571]
 [ 0.42857143  0.37142857 -0.57142857  0.11428571]
 [-1.28571429 -0.51428571  1.71428571 -0.54285714]
 [ 0.14285714 -0.14285714  0.14285714 -0.42857143]]


In [49]:
array = np.random.randint(low=0, high=6, size=(4,4))
print("datos:\n", array)

print("\ndescomposición QR:")
a = linalg.qr(array)
print(a[0])
print("\n",a[1])

datos:
 [[3 0 1 5]
 [0 0 1 4]
 [3 1 2 1]
 [0 2 1 4]]

descomposición QR:
[[-0.70710678  0.23570226 -0.21081851  0.63245553]
 [-0.          0.          0.9486833   0.31622777]
 [-0.70710678 -0.23570226  0.21081851 -0.63245553]
 [-0.         -0.94280904 -0.10540926  0.31622777]]

 [[-4.24264069 -0.70710678 -2.12132034 -4.24264069]
 [ 0.         -2.12132034 -1.1785113  -2.82842712]
 [ 0.          0.          1.05409255  2.52982213]
 [ 0.          0.          0.          5.05964426]]


In [59]:
array = np.random.randint(low=0, high=6, size=(4,4))
print("datos:\n", array)

print("\ndescomposición de valores singulares:")
a = linalg.svd(array)
for i in range(len(a)):
    print(a[i],"\n")

datos:
 [[2 5 2 5]
 [2 2 2 5]
 [3 5 4 3]
 [3 3 3 1]]

descomposición de valores singulares:
[[-0.57562213  0.3736996  -0.63524422  0.35422106]
 [-0.43490977  0.57155555  0.69251792 -0.06779882]
 [-0.58453577 -0.40866348 -0.09776582 -0.69408497]
 [-0.37125543 -0.60553036  0.32760581  0.62303838]] 

[12.88268526  3.5864159   1.71199874  0.49305358] 

[[-0.37945795 -0.60425099 -0.42483171 -0.55714489]
 [-0.32123191 -0.23653124 -0.43517951  0.80714424]
 [ 0.46966586 -0.75770903  0.41255962  0.18731138]
 [ 0.72954486  0.06935947 -0.67818241 -0.05497446]] 



In [78]:
array = np.random.randint(low=0, high=6, size=(4,4))
print("datos:\n", array)

print("\ndescomposición QR:")
a = linalg.qr(array)
for i in range(len(a)):
    print(a[i],"\n")

datos:
 [[3 1 2 0]
 [5 4 1 2]
 [2 3 3 2]
 [4 4 5 5]]

descomposición QR:
[[-0.40824829  0.70710678 -0.42613249 -0.38954387]
 [-0.68041382  0.07856742  0.72600351  0.06150693]
 [-0.27216553 -0.62853936 -0.12626148 -0.71758082]
 [-0.54433105 -0.31426968 -0.52477428  0.57406466]] 

[[-7.34846923 -6.12372436 -5.03506225 -4.62681396]
 [ 0.         -2.12132034 -1.9641855  -2.67129228]
 [ 0.          0.         -3.1289173  -1.42438732]
 [ 0.          0.          0.          1.5581755 ]] 



2

In [85]:
array = np.random.randint(low=0, high=6, size=(3,3))
print("datos:\n", array)

print("\nresultado del sistema lineal Ax = B. A y B => entrada, x => salida:")
print(linalg.solve(array,array),"\n")

print("mínimos cuadrados y = Xb, y y b => entrada, X => salida")
a = linalg.lstsq(array,array,rcond=None)
for i in range(len(a)):
    print(a[i],"\n")

datos:
 [[4 1 3]
 [0 4 3]
 [5 3 1]]

resultado del sistema lineal Ax = B. A y B => entrada, x => salida:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.12410627e-17  1.00000000e+00  0.00000000e+00]
 [-6.83214169e-17  0.00000000e+00  1.00000000e+00]] 

mínimos cuadrados y = Xb, y y b => entrada, X => salida
[[ 1.00000000e+00 -1.49031395e-15  1.48020929e-15]
 [-9.19321733e-17  1.00000000e+00 -1.09763291e-15]
 [ 1.04094426e-17  1.08292322e-15  1.00000000e+00]] 

[] 

3 

[8.14870883 3.93588139 2.02666774] 



# Generación de números aleatorios