# Álgebra lineal

Hasta el momento hemos visto cómo aplicar funciones "elemento a elemento" a matrices multidimensionales pero, en ningún caso, hemos aplicado funciones de cálculo matricial sobre las mismas. NumPy ofrece un amplio conjunto de funciones que permiten realizar multitud de tratamientos/operaciones matriciales. 

Algunas de las más comunes son:<br/>
<ul>
<li><b>diag:</b> Recupera la diagonal principal del ndarray pasado como parámetro.</li>
<li><b>dot:</b> Realiza el producto escalar de dos ndarray.</li>
<li><b>trace:</b> Calcula la suma de los elementos de la diagonal principal.</li>
<li><b>det:</b> Calcula el determinante de un ndarray.</li>
<li><b>eig:</b> Calcula los autovalores y autovectores de un ndarray.</li>
<li><b>inv:</b> Calcula la inversa de una matriz.</li>
<li><b>qr:</b> Calcula la descomposición QR de una matriz.</li>
<li><b>svd:</b> Calcula la descomposición de valores singulares (Singular Value Decomposition) de una matriz.</li>
<li><b>solve:</b> Calcula el resultado del sistema lineal Ax = B donde A y B son las matrices de entrada y x la salida.</li>
<li><b>lstsq:</b> Calcula la solución de mínimos cuadrados a y = Xb, donde y y b son los parámetros de entrada y X la salida.</li>
</ul>

In [1]:
import numpy as np
import numpy.linalg as linalg

In [2]:
array = np.random.randint(10, size=(3,3))
print("datos:\n", array)
print("\ndiagonal principal:",np.diag(array))
print("\ndiagonal por encima de la principal:",np.diag(array, k=1))
print("\ndiagonal por debajo de la principal:",np.diag(array, k=-1))

datos:
 [[8 5 7]
 [0 3 8]
 [4 8 3]]

diagonal principal: [8 3 3]

diagonal por encima de la principal: [5 8]

diagonal por debajo de la principal: [0 8]


In [3]:
array1 = np.random.randint(low=-4, high=10, size=(2,4))
array2 = np.random.randint(low=-3, high=1, size=(4,4))
print("datos1:\n", array1)
print("\ndatos2:\n", array2)

print("\nproducto escalar:\n", np.dot(array1,array2))

datos1:
 [[ 5 -1  7  0]
 [-4  4  3 -3]]

datos2:
 [[-1 -1  0  0]
 [-2 -1  0 -3]
 [-1  0 -2 -1]
 [ 0 -1 -2 -1]]

producto escalar:
 [[-10  -4 -14  -4]
 [ -7   3   0 -12]]


In [4]:
array = np.random.randint(low=-2, high=10, size=(4,4))
print("datos:\n", array)

print("\nsuma de la diagonal principal:", np.trace(array))
print("\ndeterminante:", linalg.det(array))

datos:
 [[-1  6  3  5]
 [ 3  8  2 -1]
 [ 7  9  1  6]
 [-1  0  9  9]]

suma de la diagonal principal: 17

determinante: 2925.9999999999977


In [5]:
array = np.random.randint(low=0, high=6, size=(4,4))
print("datos:\n", array)

print("\nautovalores y autovectores:\n")
a = linalg.eig(array)
print(a[0])
print("\n",a[1])

print("\nmatriz inversa:")
print(linalg.inv(array))

datos:
 [[3 5 3 5]
 [0 5 0 3]
 [5 5 2 0]
 [3 5 0 4]]

autovalores y autovectores:

[-2.78232998  4.         10.78232998  2.        ]

 [[ 0.56663988 -0.64549722  0.66504357  0.56694671]
 [ 0.13497735  0.38729833  0.24714979 -0.56694671]
 [-0.73355168 -0.64549722  0.51933448 -0.18898224]
 [-0.3501461  -0.12909944  0.47636722  0.56694671]]

matriz inversa:
[[-0.04166667 -0.29166667  0.0625      0.27083333]
 [-0.075       0.275       0.1125     -0.1125    ]
 [ 0.29166667  0.04166667  0.0625     -0.39583333]
 [ 0.125      -0.125      -0.1875      0.1875    ]]


In [6]:
array = np.random.randint(low=0, high=6, size=(4,4))
print("datos:\n", array)

print("\ndescomposición QR:")
a = linalg.qr(array)
print(a[0])
print("\n",a[1])

datos:
 [[4 5 4 4]
 [0 0 5 3]
 [5 3 3 0]
 [0 3 3 3]]

descomposición QR:
[[-0.62469505 -0.43765338  0.08295216 -0.64135369]
 [-0.          0.         -0.99173919 -0.12827074]
 [-0.78086881  0.35012271 -0.06636173  0.51308295]
 [-0.         -0.82817486 -0.07189187  0.55583986]]

 [[-6.40312424 -5.46608167 -4.84138662 -2.49878019]
 [ 0.         -3.62242339 -3.18477001 -4.23513813]
 [ 0.          0.         -5.0416481  -2.85908454]
 [ 0.          0.          0.         -1.28270737]]


In [7]:
array = np.random.randint(low=0, high=6, size=(4,4))
print("datos:\n", array)

print("\ndescomposición de valores singulares:")
a = linalg.svd(array)
for i in range(len(a)):
    print(a[i],"\n")

datos:
 [[2 0 1 5]
 [4 1 4 1]
 [2 1 0 4]
 [0 2 1 1]]

descomposición de valores singulares:
[[-0.62371966  0.42403871  0.26018817  0.60288231]
 [-0.56446892 -0.81137637  0.13408595 -0.07116307]
 [-0.5108626   0.39834767 -0.13777843 -0.74923671]
 [-0.17711023 -0.05637991 -0.94622417  0.26478877]] 

[8.16983556 4.38400924 2.05714766 0.89576418] 

[[-0.55411644 -0.17497928 -0.3743901  -0.72261281]
 [-0.36512987 -0.11993326 -0.65644175  0.64913822]
 [ 0.37973127 -0.92173297 -0.07276687 -0.03029004]
 [-0.64454582 -0.32466383  0.65086194  0.23565402]] 



In [8]:
array = np.random.randint(low=0, high=6, size=(4,4))
print("datos:\n", array)

print("\ndescomposición QR:")
a = linalg.qr(array)
for i in range(len(a)):
    print(a[i],"\n")

datos:
 [[5 4 4 3]
 [3 0 3 5]
 [1 3 1 3]
 [1 3 4 0]]

descomposición QR:
[[-0.83333333  0.09967506 -0.33142212 -0.43102183]
 [-0.5        -0.55533248  0.40507148  0.52680446]
 [-0.16666667  0.58381107 -0.33960538  0.71836971]
 [-0.16666667  0.58381107  0.78150154 -0.14367394]] 

[[-6.         -4.33333333 -5.66666667 -5.5       ]
 [ 0.          3.90156664  1.65175814 -0.72620401]
 [ 0.          0.          2.67592674  0.01227489]
 [ 0.          0.          0.          3.49606594]] 



In [9]:
array = np.random.randint(low=0, high=6, size=(3,3))
print("datos:\n", array)

print("\nresultado del sistema lineal Ax = B. A y B => entrada, x => salida:")
print(linalg.solve(array,array),"\n")

print("mínimos cuadrados y = Xb, y y b => entrada, X => salida")
a = linalg.lstsq(array,array,rcond=None)
for i in range(len(a)):
    print(a[i],"\n")

datos:
 [[4 4 3]
 [4 1 5]
 [1 5 1]]

resultado del sistema lineal Ax = B. A y B => entrada, x => salida:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

mínimos cuadrados y = Xb, y y b => entrada, X => salida
[[ 1.00000000e+00  4.21113068e-16  3.06259242e-16]
 [-4.09521230e-17  1.00000000e+00 -1.15358981e-16]
 [-1.46285196e-16 -1.11878310e-16  1.00000000e+00]] 

[] 

3 

[9.48729204 4.39153643 0.84005802] 



# Generación de números aleatorios

Aunque el core de Pyhton incluye un modulo <b>random</b> para llevar a cabo la generación de números aleatorios, NumPy ofrece una mejora sobre el mismo permitiendo generar directamente ndarrays de valores aleatorios en base a diversas distribuciones. Todas estas funciones están disponibles a través del submódulo <b>random</b>.<br/>
Algunas de las más comunes son:
<ul>
<li><b>seed:</b> Establecimiento de semilla del generador de números aleatorios.</li>
<li><b>permutation:</b> Devuelve una permutación aleatoria de una secuencia de entrada (por copia).</li>
<li><b>shuffle:</b> Aplica una permutación aleatoria sobre los elementos de la secuencia de entrada (sin copia).</li>
<li><b>rand:</b> Genera una muestra de números aleatorios utilizando una distribución uniforme.</li>
<li><b>randint:</b> Genera una muestra de números aleatorios enteros dentro de un rango definido.</li>
<li><b>randn:</b> Genera una muestra de números aleatorios utilizando una distribución normal de media 0 y desviación 1.</li>
<li><b>binomial:</b> Genera una muestra de números aleatorios utilizando una distribución binomial.</li>
<li><b>normal:</b> Genera una muestra de números aleatorios utilizando una distribución normal.</li>
<li><b>beta:</b> Genera una muestra de números aleatorios utilizando una distribución beta.</li>
<li><b>chisquare:</b> Genera una muestra de números aleatorios utilizando una distribución chi cuadrado.</li>
<li><b>gamma:</b> Genera una muestra de números aleatorios utilizando una distribución gamma.</li>
<li><b>uniform:</b> Genera una muestra de números aleatorios utilizando una distribución uniforme [0, 1).</li>
</ul>

In [10]:
import numpy as np
import numpy.random as random

In [11]:
random.permutation([1, 4, 9, 12, 15])

array([ 9, 15, 12,  4,  1])

In [12]:
arr = np.arange(10)
random.shuffle(arr)
arr

array([7, 2, 0, 1, 4, 6, 8, 9, 3, 5])

In [13]:
random.rand(2,3)

array([[0.14524235, 0.07643673, 0.26732502],
       [0.35560247, 0.49914754, 0.37223435]])

In [14]:
random.randint(10, size=(4,10))

array([[9, 9, 4, 1, 6, 2, 6, 2, 7, 3],
       [1, 9, 3, 6, 9, 2, 8, 8, 7, 8],
       [6, 8, 9, 3, 0, 7, 9, 7, 0, 1],
       [2, 6, 1, 2, 9, 2, 9, 4, 6, 4]])

In [15]:
random.randn(4,5)

array([[ 2.29315258, -1.96482454, -0.72895082,  0.76443278, -0.72229056],
       [-0.98412802,  0.79512909, -2.29918671,  1.03520871,  0.72520604],
       [ 0.29459676, -0.30643727,  0.76715847, -0.8746326 , -0.77073714],
       [-0.47472161, -1.67483844,  0.12118074, -0.60605593,  1.8539907 ]])

In [16]:
random.binomial(10, .5, size=(4,8))

array([[3, 5, 4, 8, 4, 6, 7, 6],
       [3, 4, 6, 5, 6, 9, 4, 4],
       [2, 4, 5, 5, 8, 5, 3, 7],
       [4, 8, 8, 6, 5, 4, 4, 6]])

In [17]:
mu, sigma = 0, 0.1 # mean and standard deviation
random.normal(mu, sigma, size=(4,4))

array([[ 0.01110502, -0.00762819, -0.02158158, -0.00994343],
       [-0.05680686,  0.10082303, -0.09377847,  0.08313848],
       [ 0.09412104, -0.10433691,  0.01470601,  0.06516737],
       [ 0.12888857, -0.02641013,  0.10563617, -0.01349667]])

In [18]:
random.beta(1,1,size=10)

array([0.56034414, 0.66872697, 0.67077301, 0.62428994, 0.87478701,
       0.81539373, 0.05378763, 0.14381509, 0.97106886, 0.3039049 ])

In [19]:
random.chisquare(10,(4,4))

array([[ 8.25484307, 24.17278294, 10.75796   ,  8.2103026 ],
       [15.47236257, 19.48047833,  8.22404784, 17.70547528],
       [14.5484663 , 14.01443661,  9.37117701,  7.08889243],
       [ 3.05954948, 13.40713426,  5.33598985, 13.23528843]])

In [20]:
shape, scale = 2., 2.  # mean=4, std=2*sqrt(2)
random.gamma(shape, scale, (4,4))

array([[ 2.33427536,  5.288199  ,  4.07917032,  4.72786635],
       [ 0.94745844,  7.86833711,  5.06959527,  3.97469042],
       [ 7.3945813 ,  3.26961445,  0.77447016, 10.27279364],
       [ 4.0594985 ,  4.4830924 ,  2.19899457,  3.30902289]])

In [21]:
random.uniform(low=10, high=20, size=4)

array([19.64335938, 11.51178183, 17.06339133, 11.4123281 ])