# NumPy - Ejercicios

### 1. Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la matriz principal valgan 1 y el resto valgan n.

In [2]:
import numpy as np

In [26]:
def square_matrix(n):
    a = np.full((n,n),n)
    np.fill_diagonal(a, 1)
    return a

square_matrix(5)   

array([[1, 5, 5, 5, 5],
       [5, 1, 5, 5, 5],
       [5, 5, 1, 5, 5],
       [5, 5, 5, 1, 5],
       [5, 5, 5, 5, 1]])

### 2. Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [50]:
def matrix(n, m, transpose=False):
    matrix = np.array(range(n*m))
    if transpose == True:
        return np.matrix.transpose(matrix.reshape(n,m))    
    return matrix.reshape(n,m)
 
print(matrix(5,10))
print("\n", matrix(5,10,True))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

 [[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


### 3. Crea una función que genere un esquema de tablero de ajedrez (con valores 1 y 0, enteros) en base a dos parámetros: la dimensión (cuadrada) del tablero n y un flag que indique si el primer elemento de la primera fila debe ser un 1 (True) o un 0 (False).

In [65]:
def chessboard(n, flag = True):
    chboard = np.zeros(n*n, dtype=np.int16)
    if flag == True:
        chboard[::2] = 1
    else:
        chboard[1::2] = 1
    return chboard.reshape(n,n)

print(chessboard(n))
print("\n",chessboard(n,False))

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]

 [[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


### 4. Crea una función que reciba dos arrays y genere un array que tenga 0 en todos los elementos y 1 en aquellos elementos del primer array que sean mayores que su equivalente del segundo array.

In [86]:
def matrix(arr1, arr2):
    arr_result = arr1 - arr2
    arr_result[arr_result < 0] = 0
    arr_result[arr_result > 0] = 1
    return arr_result

array1 = np.random.randint(10, size=(4,4))
array2 = np.random.randint(10, size=(4,4))

matrix(array1, array2)

array([[0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [1, 1, 1, 0]])

### 5. Crea una función que reciba un array y una tupla de enteros y devuelva la matriz resultante de seleccionar los índices de la tupla aplicados desde el final.

In [147]:
array = np.random.randint(10, size=10)
tupla = tuple(np.random.randint(10, size=10))

def build_array(p_array, p_tuple):
    return np.array([p_array,p_tuple[::-1]])

build_array(array, tupla)

array([[8, 1, 4, 3, 6, 5, 3, 0, 2, 2],
       [9, 0, 6, 1, 8, 0, 6, 9, 6, 2]])

### 6. Replica la función del ejercicio 4 utilizando la función np.where

In [177]:
def matrix(arr1, arr2):
    arr_result = np.where(arr1 - arr2 < 0, 0, 1)
    return arr_result

array1 = np.random.randint(10, size=(4,4))
array2 = np.random.randint(10, size=(4,4))

matrix(array1, array2)

array([[1, 0, 0, 1],
       [0, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 0, 0]])

### 7. Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [301]:
def any_negative(matrix):
    return np.any(a=matrix<0)

print("Example 1")
matrix = np.random.randn(4,4)
print(any_negative(matrix))
print(matrix)

print("Example 2")
matrix = np.random.randint(10, size=(4,4))
print(any_negative(matrix))
print(matrix)

Example 1
True
[[ 1.99534831  1.30598692 -0.54531563  0.27826308]
 [ 0.88622849 -1.16613945  1.57590832 -0.25414113]
 [-0.25485196 -0.02511179 -0.88850089 -0.2128875 ]
 [-0.22831505 -0.60099871  1.21543215  0.19240759]]
Example 2
False
[[1 6 2 0]
 [5 2 2 4]
 [5 6 8 8]
 [8 7 4 5]]


### 8. Crea una función que utilizando la del ejercicio anterior, sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro o devuelve "No hay negativos" en caso de que no los haya.

In [386]:
def sum_abs_negative_values(matrix):
    if any_negative(matrix):
        return np.sum(np.abs(matrix[matrix<0]))
    return "No hay negativos"

print("Example 1")
matrix = np.random.randint(low=-5, high=5, size=(4,4))
print(sum_abs_negative_values(matrix))
print(matrix)

print("Example 2")
matrix = np.random.randint(5, size=(4,4))
print(sum_abs_negative_values(matrix))
print(matrix)

Example 1
18
[[ 0  3  0 -2]
 [-2 -4  1 -2]
 [ 4 -1 -3 -4]
 [ 4  3  4  0]]
Example 2
No hay negativos
[[4 0 2 3]
 [2 3 4 2]
 [2 1 1 1]
 [2 2 0 2]]


### 9. Crea una función que reciba una matriz unidimensional con nombres, una matriz con el mismo ancho que la matriz de nombres que contenga valores numéricos y un nombre de los de la primera lista. Deberá devolver, en una tupla, los descriptivos (mínimo, máximo, media, mediana y desviación típica) del vector de valores "asociado" al nombre seleccionado por posición. Ten en cuenta que el nombre introducido puede no estar en el listado y contrólalo.

In [490]:
def selected_row_stats(names, matrix, name):
    if(name in names):
        row_selected = matrix[names == name]
        return tuple((row_selected.min(),
                      row_selected.max(), 
                      row_selected.mean(),
                      row_selected.std(),
                      np.median(row_selected)))    
    return str(name + " is not in " + np.array2string(names))

print("Scenario 1\n")
names = np.array(["ciencias", "mates", "lengua", "reli"])
matrix = np.random.randint(10,size=(len(names),len(names)))
name = "mates"
print("data:\n", matrix)
print("\nselected row", matrix[names == name])
print("\nstatistics", selected_row_stats(names, matrix, name))

print("\nScenario 2\n")
name = "phisics"
print(selected_row_stats(names, matrix, name))

Scenario 1

data:
 [[7 4 1 7]
 [5 8 0 9]
 [6 4 1 3]
 [9 3 5 7]]

selected row [[5 8 0 9]]

statistics (0, 9, 5.5, 3.5, 6.5)

Scenario 2

phisics is not in ['ciencias' 'mates' 'lengua' 'reli']


### 10. Crea una función que reciba dos matrices y devuelva la secuencia ordenada de la union de los elementos únicos de ambas.

In [510]:
def merged_matrix(matrix1:np.ndarray, matrix2:np.ndarray):
    return np.union1d(np.unique(matrix1), np.unique(matrix1))

matrix_1 = np.random.randint(20, size=(10))
matrix_2 = np.random.randint(20, size=(10))

print(matrix_1)
print(matrix_2)

merged_matrix(matrix_1,matrix_1)

[ 2 10 17 13  5 11  4  5 16  3]
[13  1 19  5 18  2  9 10  9  3]


array([ 2,  3,  4,  5, 10, 11, 13, 16, 17])