# NumPy - Ejercicios

### 1. Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la matriz principal valgan 1 y el resto valgan n.

In [2]:
import numpy as np

In [26]:
def square_matrix(n):
    a = np.full((n,n),n)
    np.fill_diagonal(a, 1)
    return a

square_matrix(5)   

array([[1, 5, 5, 5, 5],
       [5, 1, 5, 5, 5],
       [5, 5, 1, 5, 5],
       [5, 5, 5, 1, 5],
       [5, 5, 5, 5, 1]])

### 2. Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [50]:
def matrix(n, m, transpose=False):
    matrix = np.array(range(n*m))
    if transpose == True:
        return np.matrix.transpose(matrix.reshape(n,m))    
    return matrix.reshape(n,m)
 
print(matrix(5,10))
print("\n", matrix(5,10,True))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

 [[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


### 3. Crea una función que genere un esquema de tablero de ajedrez (con valores 1 y 0, enteros) en base a dos parámetros: la dimensión (cuadrada) del tablero n y un flag que indique si el primer elemento de la primera fila debe ser un 1 (True) o un 0 (False).

In [65]:
def chessboard(n, flag = True):
    chboard = np.zeros(n*n, dtype=np.int16)
    if flag == True:
        chboard[::2] = 1
    else:
        chboard[1::2] = 1
    return chboard.reshape(n,n)

print(chessboard(n))
print("\n",chessboard(n,False))

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]

 [[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


### 4. Crea una función que reciba dos arrays y genere un array que tenga 0 en todos los elementos y 1 en aquellos elementos del primer array que sean mayores que su equivalente del segundo array.

In [86]:
def matrix(arr1, arr2):
    arr_result = arr1 - arr2
    arr_result[arr_result < 0] = 0
    arr_result[arr_result > 0] = 1
    return arr_result

array1 = np.random.randint(10, size=(4,4))
array2 = np.random.randint(10, size=(4,4))

matrix(array1, array2)

array([[0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [1, 1, 1, 0]])

### 5. Crea una función que reciba un array y una tupla de enteros y devuelva la matriz resultante de seleccionar los índices de la tupla aplicados desde el final.

In [147]:
array = np.random.randint(10, size=10)
tupla = tuple(np.random.randint(10, size=10))

def build_array(p_array, p_tuple):
    return np.array([p_array,p_tuple[::-1]])

build_array(array, tupla)

array([[8, 1, 4, 3, 6, 5, 3, 0, 2, 2],
       [9, 0, 6, 1, 8, 0, 6, 9, 6, 2]])

### 6. Replica la función del ejercicio 4 utilizando la función np.where

In [177]:
def matrix(arr1, arr2):
    arr_result = np.where(arr1 - arr2 < 0, 0, 1)
    return arr_result

array1 = np.random.randint(10, size=(4,4))
array2 = np.random.randint(10, size=(4,4))

matrix(array1, array2)

array([[1, 0, 0, 1],
       [0, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 0, 0]])

### 7. Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [240]:
np.random.randn(4,4)



array([[-0.54802131,  1.35323276,  0.53992926, -0.77281946],
       [ 1.46796442, -0.76035559,  0.31429168, -0.1088888 ],
       [-1.22259481,  0.3007389 ,  1.66910975,  0.14127212],
       [-0.29029994, -0.15640059,  1.47086101, -0.98280048]])