# NumPy - Ejercicios

### 1. Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la matriz principal valgan 1 y el resto valgan n.

In [1]:
import numpy as np

In [2]:
def square_matrix(n):
    a = np.full((n,n),n)
    np.fill_diagonal(a, 1)
    return a

square_matrix(5)   

array([[1, 5, 5, 5, 5],
       [5, 1, 5, 5, 5],
       [5, 5, 1, 5, 5],
       [5, 5, 5, 1, 5],
       [5, 5, 5, 5, 1]])

### 2. Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [3]:
def matrix(n, m, transpose=False):
    matrix = np.array(range(n*m))
    if transpose == True:
        return np.matrix.transpose(matrix.reshape(n,m))    
    return matrix.reshape(n,m)
 
print(matrix(5,10))
print("\n", matrix(5,10,True))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

 [[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


### 3. Crea una función que genere un esquema de tablero de ajedrez (con valores 1 y 0, enteros) en base a dos parámetros: la dimensión (cuadrada) del tablero n y un flag que indique si el primer elemento de la primera fila debe ser un 1 (True) o un 0 (False).

In [4]:
def chessboard(n, flag = True):
    chboard = np.zeros(n*n, dtype=np.int16)
    if flag == True:
        chboard[::2] = 1
    else:
        chboard[1::2] = 1
    return chboard.reshape(n,n)

n=5
print(chessboard(n))
print("\n",chessboard(n,False))

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]

 [[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


### 4. Crea una función que reciba dos arrays y genere un array que tenga 0 en todos los elementos y 1 en aquellos elementos del primer array que sean mayores que su equivalente del segundo array.

In [5]:
def matrix(arr1, arr2):
    arr_result = arr1 - arr2
    arr_result[arr_result < 0] = 0
    arr_result[arr_result > 0] = 1
    return arr_result

array1 = np.random.randint(10, size=(4,4))
array2 = np.random.randint(10, size=(4,4))

matrix(array1, array2)

array([[0, 0, 1, 0],
       [1, 1, 0, 1],
       [0, 0, 1, 1],
       [0, 1, 1, 0]])

### 5. Crea una función que reciba un array y una tupla de enteros y devuelva la matriz resultante de seleccionar los índices de la tupla aplicados desde el final.

In [6]:
array = np.random.randint(10, size=10)
tupla = tuple(np.random.randint(10, size=10))

def build_array(p_array, p_tuple):
    return np.array([p_array,p_tuple[::-1]])

build_array(array, tupla)

array([[4, 5, 3, 2, 6, 5, 9, 7, 0, 5],
       [7, 1, 3, 3, 3, 4, 6, 4, 0, 7]])

### 6. Replica la función del ejercicio 4 utilizando la función np.where

In [7]:
def matrix(arr1, arr2):
    arr_result = np.where(arr1 - arr2 < 0, 0, 1)
    return arr_result

array1 = np.random.randint(10, size=(4,4))
array2 = np.random.randint(10, size=(4,4))

matrix(array1, array2)

array([[1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 0, 0]])

### 7. Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [8]:
def any_negative(matrix):
    return np.any(a=matrix<0)

print("Example 1")
matrix = np.random.randn(4,4)
print(any_negative(matrix))
print(matrix)

print("Example 2")
matrix = np.random.randint(10, size=(4,4))
print(any_negative(matrix))
print(matrix)

Example 1
True
[[ 1.39135519 -1.69931353  1.03364744  0.01729535]
 [-0.7421118  -0.16787966  0.32423291 -2.39769238]
 [-2.34320491 -0.47400063  0.87014055  0.15319095]
 [-0.22329871  2.49396713  0.20064431 -0.45861954]]
Example 2
False
[[5 2 7 1]
 [4 3 8 2]
 [1 5 2 1]
 [5 3 3 6]]


### 8. Crea una función que utilizando la del ejercicio anterior, sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro o devuelve "No hay negativos" en caso de que no los haya.

In [9]:
def sum_abs_negative_values(matrix):
    if any_negative(matrix):
        return np.sum(np.abs(matrix[matrix<0]))
    return "No hay negativos"

print("Example 1")
matrix = np.random.randint(low=-5, high=5, size=(4,4))
print(sum_abs_negative_values(matrix))
print(matrix)

print("Example 2")
matrix = np.random.randint(5, size=(4,4))
print(sum_abs_negative_values(matrix))
print(matrix)

Example 1
25
[[ 1 -4  2 -3]
 [-5  0  1  2]
 [-4  2 -2  1]
 [-4  4 -3  3]]
Example 2
No hay negativos
[[4 2 3 4]
 [3 4 0 3]
 [3 0 2 2]
 [4 1 3 4]]


### 9. Crea una función que reciba una matriz unidimensional con nombres, una matriz con el mismo ancho que la matriz de nombres que contenga valores numéricos y un nombre de los de la primera lista. Deberá devolver, en una tupla, los descriptivos (mínimo, máximo, media, mediana y desviación típica) del vector de valores "asociado" al nombre seleccionado por posición. Ten en cuenta que el nombre introducido puede no estar en el listado y contrólalo.

In [10]:
def selected_row_stats(names, matrix, name):
    if(name in names):
        row_selected = matrix[names == name]
        return tuple((row_selected.min(),
                      row_selected.max(), 
                      row_selected.mean(),
                      row_selected.std(),
                      np.median(row_selected)))    
    return str(name + " is not in " + np.array2string(names))

print("Scenario 1\n")
names = np.array(["ciencias", "mates", "lengua", "reli"])
matrix = np.random.randint(10,size=(len(names),len(names)))
name = "mates"
print("data:\n", matrix)
print("\nselected row", matrix[names == name])
print("\nstatistics", selected_row_stats(names, matrix, name))

print("\nScenario 2\n")
name = "phisics"
print(selected_row_stats(names, matrix, name))

Scenario 1

data:
 [[7 0 8 2]
 [2 1 5 9]
 [3 1 2 5]
 [8 7 9 2]]

selected row [[2 1 5 9]]

statistics (1, 9, 4.25, 3.112474899497183, 3.5)

Scenario 2

phisics is not in ['ciencias' 'mates' 'lengua' 'reli']


### 10. Crea una función que reciba dos matrices y devuelva la secuencia ordenada de la union de los elementos únicos de ambas.

In [11]:
def merged_matrix(matrix1:np.ndarray, matrix2:np.ndarray):
    return np.union1d(np.unique(matrix1), np.unique(matrix1))

matrix_1 = np.random.randint(20, size=(10))
matrix_2 = np.random.randint(20, size=(10))

print(matrix_1)
print(matrix_2)

merged_matrix(matrix_1,matrix_1)

[17  9 13 19 19 12  8 15 19 18]
[ 7 16 16  3 18 13 12  6 16  9]


array([ 8,  9, 12, 13, 15, 17, 18, 19])

### 11. Crea una función que reciba un número n, genere una matriz nxn a partir de una secuencia numérica y escriba la misma en un fichero cuyo nombre se recibirá también como parámetro. Hazlo con ficheros binarios.

In [12]:
def write_binary_file(n,binary_file_name):
    sequence = np.random.randn(n,n)
    np.save(binary_file_name, sequence)
    
write_binary_file(5, "binary_file_name")
print(np.load("binary_file_name.npy"))

[[ 0.44827608 -0.5623959   0.21652708 -0.71453188 -1.82783768]
 [ 0.02008981  0.57935073  2.55009375 -0.01445639 -0.06778718]
 [ 1.23607712  0.86688373  1.01797318  0.83128495  0.43104729]
 [ 1.06085398  0.19992063 -0.10020278  0.04634662 -1.8309683 ]
 [ 1.59721656  0.15656922  0.38311706  0.14931952 -0.85520633]]
