# NumPy - Ejercicios

### 1. Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la matriz principal valgan 1 y el resto valgan n.

In [1]:
import numpy as np

In [2]:
def square_matrix(n):
    a = np.full((n,n),n)
    np.fill_diagonal(a, 1)
    return a

square_matrix(5)   

array([[1, 5, 5, 5, 5],
       [5, 1, 5, 5, 5],
       [5, 5, 1, 5, 5],
       [5, 5, 5, 1, 5],
       [5, 5, 5, 5, 1]])

### 2. Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [3]:
def matrix(n, m, transpose=False):
    matrix = np.array(range(n*m))
    if transpose == True:
        return np.matrix.transpose(matrix.reshape(n,m))    
    return matrix.reshape(n,m)
 
print(matrix(5,10))
print("\n", matrix(5,10,True))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]

 [[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


### 3. Crea una función que genere un esquema de tablero de ajedrez (con valores 1 y 0, enteros) en base a dos parámetros: la dimensión (cuadrada) del tablero n y un flag que indique si el primer elemento de la primera fila debe ser un 1 (True) o un 0 (False).

In [4]:
def chessboard(n, flag = True):
    chboard = np.zeros(n*n, dtype=np.int16)
    if flag == True:
        chboard[::2] = 1
    else:
        chboard[1::2] = 1
    return chboard.reshape(n,n)

n=5
print(chessboard(n))
print("\n",chessboard(n,False))

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]

 [[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


### 4. Crea una función que reciba dos arrays y genere un array que tenga 0 en todos los elementos y 1 en aquellos elementos del primer array que sean mayores que su equivalente del segundo array.

In [5]:
def matrix(arr1, arr2):
    arr_result = arr1 - arr2
    arr_result[arr_result < 0] = 0
    arr_result[arr_result > 0] = 1
    return arr_result

array1 = np.random.randint(10, size=(4,4))
array2 = np.random.randint(10, size=(4,4))

matrix(array1, array2)

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 1, 1],
       [0, 0, 0, 0]])

### 5. Crea una función que reciba un array y una tupla de enteros y devuelva la matriz resultante de seleccionar los índices de la tupla aplicados desde el final.

In [6]:
array = np.random.randint(10, size=10)
tupla = tuple(np.random.randint(10, size=10))

def build_array(p_array, p_tuple):
    return np.array([p_array,p_tuple[::-1]])

build_array(array, tupla)

array([[0, 5, 9, 7, 1, 5, 5, 5, 6, 2],
       [3, 2, 3, 6, 8, 2, 7, 8, 1, 8]])

### 6. Replica la función del ejercicio 4 utilizando la función np.where

In [7]:
def matrix(arr1, arr2):
    arr_result = np.where(arr1 - arr2 < 0, 0, 1)
    return arr_result

array1 = np.random.randint(10, size=(4,4))
array2 = np.random.randint(10, size=(4,4))

matrix(array1, array2)

array([[1, 0, 1, 0],
       [1, 0, 0, 1],
       [1, 1, 1, 1],
       [1, 0, 0, 0]])

### 7. Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [8]:
def any_negative(matrix):
    return np.any(a=matrix<0)

print("Example 1")
matrix = np.random.randn(4,4)
print(any_negative(matrix))
print(matrix)

print("Example 2")
matrix = np.random.randint(10, size=(4,4))
print(any_negative(matrix))
print(matrix)

Example 1
True
[[ 0.47204943 -0.28607174 -0.30427569  0.26975788]
 [ 0.35591192  2.59865639 -1.0293267  -0.97090403]
 [-0.69004393  0.63868822  0.08927933  0.79754106]
 [-0.68055282  0.55242357 -1.64284546  0.61269172]]
Example 2
False
[[4 5 4 1]
 [0 0 6 8]
 [7 8 4 8]
 [6 3 9 8]]


### 8. Crea una función que utilizando la del ejercicio anterior, sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro o devuelve "No hay negativos" en caso de que no los haya.

In [9]:
def sum_abs_negative_values(matrix):
    if any_negative(matrix):
        return np.sum(np.abs(matrix[matrix<0]))
    return "No hay negativos"

print("Example 1")
matrix = np.random.randint(low=-5, high=5, size=(4,4))
print(sum_abs_negative_values(matrix))
print(matrix)

print("Example 2")
matrix = np.random.randint(5, size=(4,4))
print(sum_abs_negative_values(matrix))
print(matrix)

Example 1
26
[[-5  3  2 -5]
 [-1 -1 -5 -3]
 [ 3 -3  4  2]
 [ 3  4 -1 -2]]
Example 2
No hay negativos
[[2 3 1 1]
 [3 3 3 1]
 [3 3 3 1]
 [0 0 2 3]]


### 9. Crea una función que reciba una matriz unidimensional con nombres, una matriz con el mismo ancho que la matriz de nombres que contenga valores numéricos y un nombre de los de la primera lista. Deberá devolver, en una tupla, los descriptivos (mínimo, máximo, media, mediana y desviación típica) del vector de valores "asociado" al nombre seleccionado por posición. Ten en cuenta que el nombre introducido puede no estar en el listado y contrólalo.

In [10]:
def selected_row_stats(names, matrix, name):
    if(name in names):
        row_selected = matrix[names == name]
        return tuple((row_selected.min(),
                      row_selected.max(), 
                      row_selected.mean(),
                      row_selected.std(),
                      np.median(row_selected)))    
    return str(name + " is not in " + np.array2string(names))

print("Scenario 1\n")
names = np.array(["ciencias", "mates", "lengua", "reli"])
matrix = np.random.randint(10,size=(len(names),len(names)))
name = "mates"
print("data:\n", matrix)
print("\nselected row", matrix[names == name])
print("\nstatistics", selected_row_stats(names, matrix, name))

print("\nScenario 2\n")
name = "phisics"
print(selected_row_stats(names, matrix, name))

Scenario 1

data:
 [[2 2 3 3]
 [1 3 2 3]
 [0 6 8 2]
 [2 2 9 5]]

selected row [[1 3 2 3]]

statistics (1, 3, 2.25, 0.82915619758885, 2.5)

Scenario 2

phisics is not in ['ciencias' 'mates' 'lengua' 'reli']


### 10. Crea una función que reciba dos matrices y devuelva la secuencia ordenada de la union de los elementos únicos de ambas.

In [11]:
def merged_matrix(matrix1:np.ndarray, matrix2:np.ndarray):
    return np.union1d(np.unique(matrix1), np.unique(matrix1))

matrix_1 = np.random.randint(20, size=(10))
matrix_2 = np.random.randint(20, size=(10))

print(matrix_1)
print(matrix_2)

merged_matrix(matrix_1,matrix_1)

[18  1 13 10 14 19  9 11  0 10]
[18  8  8  2  5 15 15 16 12 15]


array([ 0,  1,  9, 10, 11, 13, 14, 18, 19])

### 11. Crea una función que reciba un número n, genere una matriz nxn a partir de una secuencia numérica y escriba la misma en un fichero cuyo nombre se recibirá también como parámetro. Hazlo con ficheros binarios.

In [12]:
def write_binary_file(n,binary_file_name):
    sequence = np.random.randn(n,n)
    np.save(binary_file_name, sequence)
    
write_binary_file(5, "numpy_file")
print(np.load("numpy_file.npy"))

[[-0.77256834 -1.75534712  0.12977545  1.64488133  0.26309473]
 [ 1.16109618  0.03206325  0.92638715  1.29646535  0.86284473]
 [ 0.37796527 -0.72079245  2.39073419 -0.12934691 -0.16737433]
 [ 2.07525094  0.10628334 -0.13288249 -0.49913436 -0.48615774]
 [ 0.78554134  0.0807458  -1.92963293  0.08423463 -1.73855812]]


### 12. Crea una función que reciba el nombre de un fichero binario de NumPy, lo lea como binario, sume el contenido del mismo por filas y guarde el resultado en un fichero de texto con el mismo nombre (pero extensión txt).

In [13]:
def rows_sum_binary_file(file_name):
    array = np.load(file_name+".npy", allow_pickle=True)
    sum_rows_array = np.sum(array, axis=1)
    np.savetxt(file_name+".txt", sum_rows_array, delimiter=',')

file_name = "numpy_file"
rows_sum_binary_file(file_name)

np.loadtxt(file_name+".txt",delimiter=',')

array([-0.49016395,  4.27885667,  1.75118576,  1.06335969, -2.71766928])

### 13. Crea una función que reciba dos enteros n y m, genere dos matrices aleatorias (normales 0,1) de dimensiones nxm y mxn y haga el producto escalar de ambas para obtener una matriz nxn. Deberá devolver una tupla con las tres matrices.

In [14]:
def dot_matrix(n,m):
    matrix_a = np.random.randn(n,m)
    matrix_b = np.random.randn(m,n)
    dot_matix = np.dot(matrix_a, matrix_b)
    return tuple((matrix_a, matrix_b, dot_matix))

dot_matrix(3,4)

(array([[-1.30149044, -1.60583865,  0.13104203, -0.09221298],
        [ 0.43678012, -0.81915234, -0.81257917, -1.36852284],
        [-1.40758136, -1.38211378,  0.46885381,  0.57817811]]),
 array([[ 0.37876291,  0.01537523,  0.74617337],
        [ 1.68444361, -1.2532648 , -0.60491878],
        [-1.36030833,  0.41408683, -0.80516614],
        [ 0.14879335, -0.07936389, -1.08755679]]),
 array([[-3.38987921,  2.05411151, -0.0049593 ],
        [-0.3126487 ,  0.80546336,  2.96404188],
        [-3.41298903,  1.8587724 , -1.22053988]]))

### 14. Crea una función que reciba una matriz de datos y un entero n y devuelva una muestra (muestreo aleatorio simple) de n elementos.

In [16]:
def random_sampling(matrix, n):
    return np.random.choice(matrix, n)

matrix = np.random.randint(50, size=10)
print(matrix)

random_sampling(matrix,3)

[31 41 30 48 10 20 38 48  4 49]


array([48, 31, 10])